-- Panini FIFA World Cup 2026 Sticker Collection - Complete Seed Data
-- 980 stickers total: 9 intro + 960 team stickers + 11 FIFA Museum
 
CREATE TABLE IF NOT EXISTS stickers (
  id            SERIAL PRIMARY KEY,
  sticker_code  VARCHAR(10)  NOT NULL,
  name          VARCHAR(255) NOT NULL,
  team          VARCHAR(100) NOT NULL,
  team_code     VARCHAR(5)   NOT NULL,
  position      INTEGER      NOT NULL,
  type          VARCHAR(20)  NOT NULL,
  is_foil       BOOLEAN      NOT NULL DEFAULT FALSE,
  group_letter  VARCHAR(2)   NOT NULL DEFAULT ''
);
 
INSERT INTO stickers (sticker_code, name, team, team_code, position, type, is_foil, group_letter) VALUES
  ('PANINI 00', 'Panini Logo', 'Panini', 'PAN0', 0, 'intro', TRUE, ''),
  ('FWC 1', 'Official Emblem', 'World Cup History', 'FWC', 1, 'fwc_special', TRUE, ''),
  ('FWC 2', 'Official Emblem', 'World Cup History', 'FWC', 2, 'fwc_special', TRUE, ''),
  ('FWC 3', 'Official Mascots', 'World Cup History', 'FWC', 3, 'fwc_special', TRUE, ''),
  ('FWC 4', 'Official Slogan', 'World Cup History', 'FWC', 4, 'fwc_special', TRUE, ''),
  ('FWC 5', 'Official Ball', 'World Cup History', 'FWC', 5, 'fwc_special', TRUE, ''),
  ('FWC 6', 'Canada - Host Countries & Cities', 'World Cup History', 'FWC', 6, 'fwc_special', TRUE, ''),
  ('FWC 7', 'Mexico - Host Countries & Cities', 'World Cup History', 'FWC', 7, 'fwc_special', TRUE, ''),
  ('FWC 8', 'USA - Host Countries & Cities', 'World Cup History', 'FWC', 8, 'fwc_special', TRUE, ''),
  ('MEX 1', 'Team Logo', 'Mexico', 'MEX', 1, 'team_logo', TRUE, 'A'),
  ('MEX 2', 'Luis Malagón', 'Mexico', 'MEX', 2, 'player', FALSE, 'A'),
  ('MEX 3', 'Johan Vasquez', 'Mexico', 'MEX', 3, 'player', FALSE, 'A'),
  ('MEX 4', 'Jorge Sánchez', 'Mexico', 'MEX', 4, 'player', FALSE, 'A'),
  ('MEX 5', 'Cesar Montes', 'Mexico', 'MEX', 5, 'player', FALSE, 'A'),
  ('MEX 6', 'Jesus Gallardo', 'Mexico', 'MEX', 6, 'player', FALSE, 'A'),
  ('MEX 7', 'Israel Reyes', 'Mexico', 'MEX', 7, 'player', FALSE, 'A'),
  ('MEX 8', 'Diego Lainez', 'Mexico', 'MEX', 8, 'player', FALSE, 'A'),
  ('MEX 9', 'Carlos Rodriguez', 'Mexico', 'MEX', 9, 'player', FALSE, 'A'),
  ('MEX 10', 'Edson Alvarez', 'Mexico', 'MEX', 10, 'player', FALSE, 'A'),
  ('MEX 11', 'Orbelin Pineda', 'Mexico', 'MEX', 11, 'player', FALSE, 'A'),
  ('MEX 12', 'Marcel Ruiz', 'Mexico', 'MEX', 12, 'player', FALSE, 'A'),
  ('MEX 13', 'Team Photo', 'Mexico', 'MEX', 13, 'team_photo', FALSE, 'A'),
  ('MEX 14', 'Érick Sánchez', 'Mexico', 'MEX', 14, 'player', FALSE, 'A'),
  ('MEX 15', 'Hirving Lozano', 'Mexico', 'MEX', 15, 'player', FALSE, 'A'),
  ('MEX 16', 'Santiago Giménez', 'Mexico', 'MEX', 16, 'player', FALSE, 'A'),
  ('MEX 17', 'Raúl Jiménez', 'Mexico', 'MEX', 17, 'player', FALSE, 'A'),
  ('MEX 18', 'Alexis Vega', 'Mexico', 'MEX', 18, 'player', FALSE, 'A'),
  ('MEX 19', 'Roberto Alvarado', 'Mexico', 'MEX', 19, 'player', FALSE, 'A'),
  ('MEX 20', 'Cesar Huerta', 'Mexico', 'MEX', 20, 'player', FALSE, 'A'),
  ('RSA 1', 'Team Logo', 'South Africa', 'RSA', 1, 'team_logo', TRUE, 'A'),
  ('RSA 2', 'Ronwen Williams', 'South Africa', 'RSA', 2, 'player', FALSE, 'A'),
  ('RSA 3', 'Sipho Chaine', 'South Africa', 'RSA', 3, 'player', FALSE, 'A'),
  ('RSA 4', 'Aubrey Modiba', 'South Africa', 'RSA', 4, 'player', FALSE, 'A'),
  ('RSA 5', 'Samukele Kabini', 'South Africa', 'RSA', 5, 'player', FALSE, 'A'),
  ('RSA 6', 'Mbekezeli Mbokazi', 'South Africa', 'RSA', 6, 'player', FALSE, 'A'),
  ('RSA 7', 'Khulumani Ndamane', 'South Africa', 'RSA', 7, 'player', FALSE, 'A'),
  ('RSA 8', 'Siyabonga Ngezana', 'South Africa', 'RSA', 8, 'player', FALSE, 'A'),
  ('RSA 9', 'Khuliso Mudau', 'South Africa', 'RSA', 9, 'player', FALSE, 'A'),
  ('RSA 10', 'Nkosinathi Sibisi', 'South Africa', 'RSA', 10, 'player', FALSE, 'A'),
  ('RSA 11', 'Teboho Mokoena', 'South Africa', 'RSA', 11, 'player', FALSE, 'A'),
  ('RSA 12', 'Thalente Mbatha', 'South Africa', 'RSA', 12, 'player', FALSE, 'A'),
  ('RSA 13', 'Team Photo', 'South Africa', 'RSA', 13, 'team_photo', FALSE, 'A'),
  ('RSA 14', 'Bathasi Aubaas', 'South Africa', 'RSA', 14, 'player', FALSE, 'A'),
  ('RSA 15', 'Yaya Sithole', 'South Africa', 'RSA', 15, 'player', FALSE, 'A'),
  ('RSA 16', 'Sipho Mbule', 'South Africa', 'RSA', 16, 'player', FALSE, 'A'),
  ('RSA 17', 'Lyle Foster', 'South Africa', 'RSA', 17, 'player', FALSE, 'A'),
  ('RSA 18', 'Iqraam Rayners', 'South Africa', 'RSA', 18, 'player', FALSE, 'A'),
  ('RSA 19', 'Mohau Nkota', 'South Africa', 'RSA', 19, 'player', FALSE, 'A'),
  ('RSA 20', 'Oswin Appollis', 'South Africa', 'RSA', 20, 'player', FALSE, 'A'),
  ('KOR 1', 'Team Logo', 'South Korea', 'KOR', 1, 'team_logo', TRUE, 'A'),
  ('KOR 2', 'Hyeon-woo Jo', 'South Korea', 'KOR', 2, 'player', FALSE, 'A'),
  ('KOR 3', 'Seung-Gyu Kim', 'South Korea', 'KOR', 3, 'player', FALSE, 'A'),
  ('KOR 4', 'Min-jae Kim', 'South Korea', 'KOR', 4, 'player', FALSE, 'A'),
  ('KOR 5', 'Yu-min Cho', 'South Korea', 'KOR', 5, 'player', FALSE, 'A'),
  ('KOR 6', 'Young-woo Seol', 'South Korea', 'KOR', 6, 'player', FALSE, 'A'),
  ('KOR 7', 'Han-beom Lee', 'South Korea', 'KOR', 7, 'player', FALSE, 'A'),
  ('KOR 8', 'Tae-seok Lee', 'South Korea', 'KOR', 8, 'player', FALSE, 'A'),
  ('KOR 9', 'Myung-jae Lee', 'South Korea', 'KOR', 9, 'player', FALSE, 'A'),
  ('KOR 10', 'Jae-sung Lee', 'South Korea', 'KOR', 10, 'player', FALSE, 'A'),
  ('KOR 11', 'In-beom Hwang', 'South Korea', 'KOR', 11, 'player', FALSE, 'A'),
  ('KOR 12', 'Kang-in Lee', 'South Korea', 'KOR', 12, 'player', FALSE, 'A'),
  ('KOR 13', 'Team Photo', 'South Korea', 'KOR', 13, 'team_photo', FALSE, 'A'),
  ('KOR 14', 'Seung-ho Paik', 'South Korea', 'KOR', 14, 'player', FALSE, 'A'),
  ('KOR 15', 'Jens Castrop', 'South Korea', 'KOR', 15, 'player', FALSE, 'A'),
  ('KOR 16', 'Dongg-yeong Lee', 'South Korea', 'KOR', 16, 'player', FALSE, 'A'),
  ('KOR 17', 'Gue-sung Cho', 'South Korea', 'KOR', 17, 'player', FALSE, 'A'),
  ('KOR 18', 'Heung-min Son', 'South Korea', 'KOR', 18, 'player', FALSE, 'A'),
  ('KOR 19', 'Hee-chan Hwang', 'South Korea', 'KOR', 19, 'player', FALSE, 'A'),
  ('KOR 20', 'Hyeon-Gyu Oh', 'South Korea', 'KOR', 20, 'player', FALSE, 'A'),
  ('CZE 1', 'Team Logo', 'Czechia', 'CZE', 1, 'team_logo', TRUE, 'A'),
  ('CZE 2', 'Matej Kovar', 'Czechia', 'CZE', 2, 'player', FALSE, 'A'),
  ('CZE 3', 'Jindrich Stanek', 'Czechia', 'CZE', 3, 'player', FALSE, 'A'),
  ('CZE 4', 'Ladislav Krejci', 'Czechia', 'CZE', 4, 'player', FALSE, 'A'),
  ('CZE 5', 'Vladimir Coufal', 'Czechia', 'CZE', 5, 'player', FALSE, 'A'),
  ('CZE 6', 'Jaroslav Zeleny', 'Czechia', 'CZE', 6, 'player', FALSE, 'A'),
  ('CZE 7', 'Tomas Holes', 'Czechia', 'CZE', 7, 'player', FALSE, 'A'),
  ('CZE 8', 'David Zima', 'Czechia', 'CZE', 8, 'player', FALSE, 'A'),
  ('CZE 9', 'Michal Sadilek', 'Czechia', 'CZE', 9, 'player', FALSE, 'A'),
  ('CZE 10', 'Lukas Provod', 'Czechia', 'CZE', 10, 'player', FALSE, 'A'),
  ('CZE 11', 'Lukas Cerv', 'Czechia', 'CZE', 11, 'player', FALSE, 'A'),
  ('CZE 12', 'Tomas Soucek', 'Czechia', 'CZE', 12, 'player', FALSE, 'A'),
  ('CZE 13', 'Team Photo', 'Czechia', 'CZE', 13, 'team_photo', FALSE, 'A'),
  ('CZE 14', 'Pavel Sulc', 'Czechia', 'CZE', 14, 'player', FALSE, 'A'),
  ('CZE 15', 'Matej Vydra', 'Czechia', 'CZE', 15, 'player', FALSE, 'A'),
  ('CZE 16', 'Vasil Kusej', 'Czechia', 'CZE', 16, 'player', FALSE, 'A'),
  ('CZE 17', 'Tomas Chory', 'Czechia', 'CZE', 17, 'player', FALSE, 'A'),
  ('CZE 18', 'Vaclav Cerny', 'Czechia', 'CZE', 18, 'player', FALSE, 'A'),
  ('CZE 19', 'Adam Hlozek', 'Czechia', 'CZE', 19, 'player', FALSE, 'A'),
  ('CZE 20', 'Patrik Schick', 'Czechia', 'CZE', 20, 'player', FALSE, 'A'),
  ('CAN 1', 'Team Logo', 'Canada', 'CAN', 1, 'team_logo', TRUE, 'B'),
  ('CAN 2', 'Dayne St.Clair', 'Canada', 'CAN', 2, 'player', FALSE, 'B'),
  ('CAN 3', 'Alphonso Davies', 'Canada', 'CAN', 3, 'player', FALSE, 'B'),
  ('CAN 4', 'Alistair Johnston', 'Canada', 'CAN', 4, 'player', FALSE, 'B'),
  ('CAN 5', 'Samuel Adekugbe', 'Canada', 'CAN', 5, 'player', FALSE, 'B'),
  ('CAN 6', 'Riche Larvea', 'Canada', 'CAN', 6, 'player', FALSE, 'B'),
  ('CAN 7', 'Derek Cornelius', 'Canada', 'CAN', 7, 'player', FALSE, 'B'),
  ('CAN 8', 'Moïse Bombito', 'Canada', 'CAN', 8, 'player', FALSE, 'B'),
  ('CAN 9', 'Kamal Miller', 'Canada', 'CAN', 9, 'player', FALSE, 'B'),
  ('CAN 10', 'Stephen Eustáquio', 'Canada', 'CAN', 10, 'player', FALSE, 'B'),
  ('CAN 11', 'Ismaël Koné', 'Canada', 'CAN', 11, 'player', FALSE, 'B'),
  ('CAN 12', 'Jonathan Osorio', 'Canada', 'CAN', 12, 'player', FALSE, 'B'),
  ('CAN 13', 'Team Photo', 'Canada', 'CAN', 13, 'team_photo', FALSE, 'B'),
  ('CAN 14', 'Jacob Shaffelburg', 'Canada', 'CAN', 14, 'player', FALSE, 'B'),
  ('CAN 15', 'Mathieu Choinière', 'Canada', 'CAN', 15, 'player', FALSE, 'B'),
  ('CAN 16', 'Niko Sigur', 'Canada', 'CAN', 16, 'player', FALSE, 'B'),
  ('CAN 17', 'Tajon Buchanan', 'Canada', 'CAN', 17, 'player', FALSE, 'B'),
  ('CAN 18', 'Liam Millar', 'Canada', 'CAN', 18, 'player', FALSE, 'B'),
  ('CAN 19', 'Cyle Larin', 'Canada', 'CAN', 19, 'player', FALSE, 'B'),
  ('CAN 20', 'Jonathan David', 'Canada', 'CAN', 20, 'player', FALSE, 'B'),
  ('BIH 1', 'Team Logo', 'Bosnia and Herzegovina', 'BIH', 1, 'team_logo', TRUE, 'B'),
  ('BIH 2', 'Nikola Vasilj', 'Bosnia and Herzegovina', 'BIH', 2, 'player', FALSE, 'B'),
  ('BIH 3', 'Amer Dedic', 'Bosnia and Herzegovina', 'BIH', 3, 'player', FALSE, 'B'),
  ('BIH 4', 'Sead Kolasinac', 'Bosnia and Herzegovina', 'BIH', 4, 'player', FALSE, 'B'),
  ('BIH 5', 'Tarik Muharemovic', 'Bosnia and Herzegovina', 'BIH', 5, 'player', FALSE, 'B'),
  ('BIH 6', 'Nihad Mujakic', 'Bosnia and Herzegovina', 'BIH', 6, 'player', FALSE, 'B'),
  ('BIH 7', 'Nikola Katic', 'Bosnia and Herzegovina', 'BIH', 7, 'player', FALSE, 'B'),
  ('BIH 8', 'Amir Hadziahmetovic', 'Bosnia and Herzegovina', 'BIH', 8, 'player', FALSE, 'B'),
  ('BIH 9', 'Benjamin Tahirovic', 'Bosnia and Herzegovina', 'BIH', 9, 'player', FALSE, 'B'),
  ('BIH 10', 'Armin Gigovic', 'Bosnia and Herzegovina', 'BIH', 10, 'player', FALSE, 'B'),
  ('BIH 11', 'Ivan Sunjic', 'Bosnia and Herzegovina', 'BIH', 11, 'player', FALSE, 'B'),
  ('BIH 12', 'Ivan Basic', 'Bosnia and Herzegovina', 'BIH', 12, 'player', FALSE, 'B'),
  ('BIH 13', 'Team Photo', 'Bosnia and Herzegovina', 'BIH', 13, 'team_photo', FALSE, 'B'),
  ('BIH 14', 'Dzenis Burnic', 'Bosnia and Herzegovina', 'BIH', 14, 'player', FALSE, 'B'),
  ('BIH 15', 'Esmir Bajraktarevic', 'Bosnia and Herzegovina', 'BIH', 15, 'player', FALSE, 'B'),
  ('BIH 16', 'Amar Memic', 'Bosnia and Herzegovina', 'BIH', 16, 'player', FALSE, 'B'),
  ('BIH 17', 'Ermedin Demirovic', 'Bosnia and Herzegovina', 'BIH', 17, 'player', FALSE, 'B'),
  ('BIH 18', 'Edin Dzeko', 'Bosnia and Herzegovina', 'BIH', 18, 'player', FALSE, 'B'),
  ('BIH 19', 'Samed Bazdar', 'Bosnia and Herzegovina', 'BIH', 19, 'player', FALSE, 'B'),
  ('BIH 20', 'Haris Tabakovic', 'Bosnia and Herzegovina', 'BIH', 20, 'player', FALSE, 'B'),
  ('QAT 1', 'Team Logo', 'Qatar', 'QAT', 1, 'team_logo', TRUE, 'B'),
  ('QAT 2', 'Meshaal Barsham', 'Qatar', 'QAT', 2, 'player', FALSE, 'B'),
  ('QAT 3', 'Sultan Albrake', 'Qatar', 'QAT', 3, 'player', FALSE, 'B'),
  ('QAT 4', 'Lucas Mendes', 'Qatar', 'QAT', 4, 'player', FALSE, 'B'),
  ('QAT 5', 'Homam Ahmed', 'Qatar', 'QAT', 5, 'player', FALSE, 'B'),
  ('QAT 6', 'Boualem Khoukhi', 'Qatar', 'QAT', 6, 'player', FALSE, 'B'),
  ('QAT 7', 'Pedro Miguel', 'Qatar', 'QAT', 7, 'player', FALSE, 'B'),
  ('QAT 8', 'Tarek Salman', 'Qatar', 'QAT', 8, 'player', FALSE, 'B'),
  ('QAT 9', 'Mohamed Al-Mannai', 'Qatar', 'QAT', 9, 'player', FALSE, 'B'),
  ('QAT 10', 'Karim Boudiaf', 'Qatar', 'QAT', 10, 'player', FALSE, 'B'),
  ('QAT 11', 'Assim Madibo', 'Qatar', 'QAT', 11, 'player', FALSE, 'B'),
  ('QAT 12', 'Ahmed Fatehi', 'Qatar', 'QAT', 12, 'player', FALSE, 'B'),
  ('QAT 13', 'Team Photo', 'Qatar', 'QAT', 13, 'team_photo', FALSE, 'B'),
  ('QAT 14', 'Mohammed Waad', 'Qatar', 'QAT', 14, 'player', FALSE, 'B'),
  ('QAT 15', 'Abdulaziz Hatem', 'Qatar', 'QAT', 15, 'player', FALSE, 'B'),
  ('QAT 16', 'Hassan Al-Haydos', 'Qatar', 'QAT', 16, 'player', FALSE, 'B'),
  ('QAT 17', 'Edmilson Junior', 'Qatar', 'QAT', 17, 'player', FALSE, 'B'),
  ('QAT 18', 'Akram Hassan Afif', 'Qatar', 'QAT', 18, 'player', FALSE, 'B'),
  ('QAT 19', 'Ahmed Al Ganehi', 'Qatar', 'QAT', 19, 'player', FALSE, 'B'),
  ('QAT 20', 'Almoez Ali', 'Qatar', 'QAT', 20, 'player', FALSE, 'B'),
  ('SUI 1', 'Team Logo', 'Switzerland', 'SUI', 1, 'team_logo', TRUE, 'B'),
  ('SUI 2', 'Gregor Kobel', 'Switzerland', 'SUI', 2, 'player', FALSE, 'B'),
  ('SUI 3', 'Yvon Mvogo', 'Switzerland', 'SUI', 3, 'player', FALSE, 'B'),
  ('SUI 4', 'Manuel Akanji', 'Switzerland', 'SUI', 4, 'player', FALSE, 'B'),
  ('SUI 5', 'Ricardo Rodriguez', 'Switzerland', 'SUI', 5, 'player', FALSE, 'B'),
  ('SUI 6', 'Nico Elvedi', 'Switzerland', 'SUI', 6, 'player', FALSE, 'B'),
  ('SUI 7', 'Aurèle Amenda', 'Switzerland', 'SUI', 7, 'player', FALSE, 'B'),
  ('SUI 8', 'Silvan Widmer', 'Switzerland', 'SUI', 8, 'player', FALSE, 'B'),
  ('SUI 9', 'Granit Xhaka', 'Switzerland', 'SUI', 9, 'player', FALSE, 'B'),
  ('SUI 10', 'Denis Zakaria', 'Switzerland', 'SUI', 10, 'player', FALSE, 'B'),
  ('SUI 11', 'Remo Freuler', 'Switzerland', 'SUI', 11, 'player', FALSE, 'B'),
  ('SUI 12', 'Fabian Rieder', 'Switzerland', 'SUI', 12, 'player', FALSE, 'B'),
  ('SUI 13', 'Team Photo', 'Switzerland', 'SUI', 13, 'team_photo', FALSE, 'B'),
  ('SUI 14', 'Ardon Jashari', 'Switzerland', 'SUI', 14, 'player', FALSE, 'B'),
  ('SUI 15', 'Johan Manzambi', 'Switzerland', 'SUI', 15, 'player', FALSE, 'B'),
  ('SUI 16', 'Michel Aebischer', 'Switzerland', 'SUI', 16, 'player', FALSE, 'B'),
  ('SUI 17', 'Breel Embolo', 'Switzerland', 'SUI', 17, 'player', FALSE, 'B'),
  ('SUI 18', 'Ruben Vargas', 'Switzerland', 'SUI', 18, 'player', FALSE, 'B'),
  ('SUI 19', 'Dan Ndoye', 'Switzerland', 'SUI', 19, 'player', FALSE, 'B'),
  ('SUI 20', 'Zeki Amdouni', 'Switzerland', 'SUI', 20, 'player', FALSE, 'B'),
  ('BRA 1', 'Team Logo', 'Brazil', 'BRA', 1, 'team_logo', TRUE, 'C'),
  ('BRA 2', 'Alisson', 'Brazil', 'BRA', 2, 'player', FALSE, 'C'),
  ('BRA 3', 'Bento', 'Brazil', 'BRA', 3, 'player', FALSE, 'C'),
  ('BRA 4', 'Marquinhos', 'Brazil', 'BRA', 4, 'player', FALSE, 'C'),
  ('BRA 5', 'Éder Militão', 'Brazil', 'BRA', 5, 'player', FALSE, 'C'),
  ('BRA 6', 'Gabriel Magalhães', 'Brazil', 'BRA', 6, 'player', FALSE, 'C'),
  ('BRA 7', 'Danilo', 'Brazil', 'BRA', 7, 'player', FALSE, 'C'),
  ('BRA 8', 'Wesley', 'Brazil', 'BRA', 8, 'player', FALSE, 'C'),
  ('BRA 9', 'Lucas Paquetá', 'Brazil', 'BRA', 9, 'player', FALSE, 'C'),
  ('BRA 10', 'Casemiro', 'Brazil', 'BRA', 10, 'player', FALSE, 'C'),
  ('BRA 11', 'Bruno Guimarães', 'Brazil', 'BRA', 11, 'player', FALSE, 'C'),
  ('BRA 12', 'Luiz Henrique', 'Brazil', 'BRA', 12, 'player', FALSE, 'C'),
  ('BRA 13', 'Team Photo', 'Brazil', 'BRA', 13, 'team_photo', FALSE, 'C'),
  ('BRA 14', 'Vinicius Júnior', 'Brazil', 'BRA', 14, 'player', FALSE, 'C'),
  ('BRA 15', 'Rodrygo', 'Brazil', 'BRA', 15, 'player', FALSE, 'C'),
  ('BRA 16', 'João Pedro', 'Brazil', 'BRA', 16, 'player', FALSE, 'C'),
  ('BRA 17', 'Matheus Cunha', 'Brazil', 'BRA', 17, 'player', FALSE, 'C'),
  ('BRA 18', 'Gabriel Martinelli', 'Brazil', 'BRA', 18, 'player', FALSE, 'C'),
  ('BRA 19', 'Raphinha', 'Brazil', 'BRA', 19, 'player', FALSE, 'C'),
  ('BRA 20', 'Estévão', 'Brazil', 'BRA', 20, 'player', FALSE, 'C'),
  ('MAR 1', 'Team Logo', 'Morocco', 'MAR', 1, 'team_logo', TRUE, 'C'),
  ('MAR 2', 'Yassine Bounou', 'Morocco', 'MAR', 2, 'player', FALSE, 'C'),
  ('MAR 3', 'Munir El Kajoui', 'Morocco', 'MAR', 3, 'player', FALSE, 'C'),
  ('MAR 4', 'Achraf Hakimi', 'Morocco', 'MAR', 4, 'player', FALSE, 'C'),
  ('MAR 5', 'Noussair Mazraoui', 'Morocco', 'MAR', 5, 'player', FALSE, 'C'),
  ('MAR 6', 'Nayef Aguerd', 'Morocco', 'MAR', 6, 'player', FALSE, 'C'),
  ('MAR 7', 'Roman Saiss', 'Morocco', 'MAR', 7, 'player', FALSE, 'C'),
  ('MAR 8', 'Jawad El Yamio', 'Morocco', 'MAR', 8, 'player', FALSE, 'C'),
  ('MAR 9', 'Adam Masina', 'Morocco', 'MAR', 9, 'player', FALSE, 'C'),
  ('MAR 10', 'Sofyan Amrabat', 'Morocco', 'MAR', 10, 'player', FALSE, 'C'),
  ('MAR 11', 'Azzedine Ounahi', 'Morocco', 'MAR', 11, 'player', FALSE, 'C'),
  ('MAR 12', 'Eliesse Ben Seghir', 'Morocco', 'MAR', 12, 'player', FALSE, 'C'),
  ('MAR 13', 'Team Photo', 'Morocco', 'MAR', 13, 'team_photo', FALSE, 'C'),
  ('MAR 14', 'Bilal El Khannouss', 'Morocco', 'MAR', 14, 'player', FALSE, 'C'),
  ('MAR 15', 'Ismael Saibari', 'Morocco', 'MAR', 15, 'player', FALSE, 'C'),
  ('MAR 16', 'Youssef En-Nesyri', 'Morocco', 'MAR', 16, 'player', FALSE, 'C'),
  ('MAR 17', 'Abde Ezzalzouli', 'Morocco', 'MAR', 17, 'player', FALSE, 'C'),
  ('MAR 18', 'Soufiane Rahimi', 'Morocco', 'MAR', 18, 'player', FALSE, 'C'),
  ('MAR 19', 'Brahim Diaz', 'Morocco', 'MAR', 19, 'player', FALSE, 'C'),
  ('MAR 20', 'Ayoub El Kaabi', 'Morocco', 'MAR', 20, 'player', FALSE, 'C'),
  ('HAI 1', 'Team Logo', 'Haiti', 'HAI', 1, 'team_logo', TRUE, 'C'),
  ('HAI 2', 'Johny Placide', 'Haiti', 'HAI', 2, 'player', FALSE, 'C'),
  ('HAI 3', 'Carlens Arcus', 'Haiti', 'HAI', 3, 'player', FALSE, 'C'),
  ('HAI 4', 'Martin Expérience', 'Haiti', 'HAI', 4, 'player', FALSE, 'C'),
  ('HAI 5', 'Jean-Kevin Duverne', 'Haiti', 'HAI', 5, 'player', FALSE, 'C'),
  ('HAI 6', 'Ricardo Adé', 'Haiti', 'HAI', 6, 'player', FALSE, 'C'),
  ('HAI 7', 'Duke Lacroix', 'Haiti', 'HAI', 7, 'player', FALSE, 'C'),
  ('HAI 8', 'Garven Metusala', 'Haiti', 'HAI', 8, 'player', FALSE, 'C'),
  ('HAI 9', 'Hannes Delcroix', 'Haiti', 'HAI', 9, 'player', FALSE, 'C'),
  ('HAI 10', 'Leverton Pierre', 'Haiti', 'HAI', 10, 'player', FALSE, 'C'),
  ('HAI 11', 'Danley Jean Jacques', 'Haiti', 'HAI', 11, 'player', FALSE, 'C'),
  ('HAI 12', 'Jean-Ricner Bellegarde', 'Haiti', 'HAI', 12, 'player', FALSE, 'C'),
  ('HAI 13', 'Team Photo', 'Haiti', 'HAI', 13, 'team_photo', FALSE, 'C'),
  ('HAI 14', 'Christopher Attys', 'Haiti', 'HAI', 14, 'player', FALSE, 'C'),
  ('HAI 15', 'Derrick Etienne Jr', 'Haiti', 'HAI', 15, 'player', FALSE, 'C'),
  ('HAI 16', 'Josue Casimir', 'Haiti', 'HAI', 16, 'player', FALSE, 'C'),
  ('HAI 17', 'Ruben Providence', 'Haiti', 'HAI', 17, 'player', FALSE, 'C'),
  ('HAI 18', 'Duckens Nazon', 'Haiti', 'HAI', 18, 'player', FALSE, 'C'),
  ('HAI 19', 'Louicius Deedson', 'Haiti', 'HAI', 19, 'player', FALSE, 'C'),
  ('HAI 20', 'Frantzdy Pierrot', 'Haiti', 'HAI', 20, 'player', FALSE, 'C'),
  ('SCO 1', 'Team Logo', 'Scotland', 'SCO', 1, 'team_logo', TRUE, 'C'),
  ('SCO 2', 'Angus Gunn', 'Scotland', 'SCO', 2, 'player', FALSE, 'C'),
  ('SCO 3', 'Jack Hendry', 'Scotland', 'SCO', 3, 'player', FALSE, 'C'),
  ('SCO 4', 'Kieran Tierney', 'Scotland', 'SCO', 4, 'player', FALSE, 'C'),
  ('SCO 5', 'Aaron Hickey', 'Scotland', 'SCO', 5, 'player', FALSE, 'C'),
  ('SCO 6', 'Andrew Robertson', 'Scotland', 'SCO', 6, 'player', FALSE, 'C'),
  ('SCO 7', 'Scott McKenna', 'Scotland', 'SCO', 7, 'player', FALSE, 'C'),
  ('SCO 8', 'John Souttar', 'Scotland', 'SCO', 8, 'player', FALSE, 'C'),
  ('SCO 9', 'Anthony Ralston', 'Scotland', 'SCO', 9, 'player', FALSE, 'C'),
  ('SCO 10', 'Grant Hanley', 'Scotland', 'SCO', 10, 'player', FALSE, 'C'),
  ('SCO 11', 'Scott McTominay', 'Scotland', 'SCO', 11, 'player', FALSE, 'C'),
  ('SCO 12', 'Billy Gilmour', 'Scotland', 'SCO', 12, 'player', FALSE, 'C'),
  ('SCO 13', 'Team Photo', 'Scotland', 'SCO', 13, 'team_photo', FALSE, 'C'),
  ('SCO 14', 'Lewis Ferguson', 'Scotland', 'SCO', 14, 'player', FALSE, 'C'),
  ('SCO 15', 'Ryan Christie', 'Scotland', 'SCO', 15, 'player', FALSE, 'C'),
  ('SCO 16', 'Kenny McLean', 'Scotland', 'SCO', 16, 'player', FALSE, 'C'),
  ('SCO 17', 'John McGinn', 'Scotland', 'SCO', 17, 'player', FALSE, 'C'),
  ('SCO 18', 'Lyndon Dykes', 'Scotland', 'SCO', 18, 'player', FALSE, 'C'),
  ('SCO 19', 'Che Adams', 'Scotland', 'SCO', 19, 'player', FALSE, 'C'),
  ('SCO 20', 'Ben Gannon-Doak', 'Scotland', 'SCO', 20, 'player', FALSE, 'C'),
  ('USA 1', 'Team Logo', 'USA', 'USA', 1, 'team_logo', TRUE, 'D'),
  ('USA 2', 'Matt Freese', 'USA', 'USA', 2, 'player', FALSE, 'D'),
  ('USA 3', 'Chris Richards', 'USA', 'USA', 3, 'player', FALSE, 'D'),
  ('USA 4', 'Tim Ream', 'USA', 'USA', 4, 'player', FALSE, 'D'),
  ('USA 5', 'Mark McKenzie', 'USA', 'USA', 5, 'player', FALSE, 'D'),
  ('USA 6', 'Alex Freeman', 'USA', 'USA', 6, 'player', FALSE, 'D'),
  ('USA 7', 'Antonee Robinson', 'USA', 'USA', 7, 'player', FALSE, 'D'),
  ('USA 8', 'Tyler Adams', 'USA', 'USA', 8, 'player', FALSE, 'D'),
  ('USA 9', 'Tanner Tessmann', 'USA', 'USA', 9, 'player', FALSE, 'D'),
  ('USA 10', 'Weston McKennie', 'USA', 'USA', 10, 'player', FALSE, 'D'),
  ('USA 11', 'Christian Roldan', 'USA', 'USA', 11, 'player', FALSE, 'D'),
  ('USA 12', 'Timothy Weah', 'USA', 'USA', 12, 'player', FALSE, 'D'),
  ('USA 13', 'Team Photo', 'USA', 'USA', 13, 'team_photo', FALSE, 'D'),
  ('USA 14', 'Diego Luna', 'USA', 'USA', 14, 'player', FALSE, 'D'),
  ('USA 15', 'Malik Tillman', 'USA', 'USA', 15, 'player', FALSE, 'D'),
  ('USA 16', 'Christian Pulisic', 'USA', 'USA', 16, 'player', FALSE, 'D'),
  ('USA 17', 'Brenden Aaronson', 'USA', 'USA', 17, 'player', FALSE, 'D'),
  ('USA 18', 'Ricardo Pepi', 'USA', 'USA', 18, 'player', FALSE, 'D'),
  ('USA 19', 'Haji Wright', 'USA', 'USA', 19, 'player', FALSE, 'D'),
  ('USA 20', 'Folarin Balogun', 'USA', 'USA', 20, 'player', FALSE, 'D'),
  ('PAR 1', 'Team Logo', 'Paraguay', 'PAR', 1, 'team_logo', TRUE, 'D'),
  ('PAR 2', 'Roberto Fernandez', 'Paraguay', 'PAR', 2, 'player', FALSE, 'D'),
  ('PAR 3', 'Orlando Gill', 'Paraguay', 'PAR', 3, 'player', FALSE, 'D'),
  ('PAR 4', 'Gustavo Gomez', 'Paraguay', 'PAR', 4, 'player', FALSE, 'D'),
  ('PAR 5', 'Fabián Balbuena', 'Paraguay', 'PAR', 5, 'player', FALSE, 'D'),
  ('PAR 6', 'Juan José Cáceres', 'Paraguay', 'PAR', 6, 'player', FALSE, 'D'),
  ('PAR 7', 'Omar Alderete', 'Paraguay', 'PAR', 7, 'player', FALSE, 'D'),
  ('PAR 8', 'Junior Alonso', 'Paraguay', 'PAR', 8, 'player', FALSE, 'D'),
  ('PAR 9', 'Mathías Villasanti', 'Paraguay', 'PAR', 9, 'player', FALSE, 'D'),
  ('PAR 10', 'Diego Gomez', 'Paraguay', 'PAR', 10, 'player', FALSE, 'D'),
  ('PAR 11', 'Damián Bobadilla', 'Paraguay', 'PAR', 11, 'player', FALSE, 'D'),
  ('PAR 12', 'Andres Cubas', 'Paraguay', 'PAR', 12, 'player', FALSE, 'D'),
  ('PAR 13', 'Team Photo', 'Paraguay', 'PAR', 13, 'team_photo', FALSE, 'D'),
  ('PAR 14', 'Matias Galarza Fonda', 'Paraguay', 'PAR', 14, 'player', FALSE, 'D'),
  ('PAR 15', 'Julio Enciso', 'Paraguay', 'PAR', 15, 'player', FALSE, 'D'),
  ('PAR 16', 'Alejandro Romero Gamarra', 'Paraguay', 'PAR', 16, 'player', FALSE, 'D'),
  ('PAR 17', 'Miguel Almirón', 'Paraguay', 'PAR', 17, 'player', FALSE, 'D'),
  ('PAR 18', 'Ramon Sosa', 'Paraguay', 'PAR', 18, 'player', FALSE, 'D'),
  ('PAR 19', 'Angel Romero', 'Paraguay', 'PAR', 19, 'player', FALSE, 'D'),
  ('PAR 20', 'Antonio Sanabria', 'Paraguay', 'PAR', 20, 'player', FALSE, 'D'),
  ('AUS 1', 'Team Logo', 'Australia', 'AUS', 1, 'team_logo', TRUE, 'D'),
  ('AUS 2', 'Mathew Ryan', 'Australia', 'AUS', 2, 'player', FALSE, 'D'),
  ('AUS 3', 'Joe Gauci', 'Australia', 'AUS', 3, 'player', FALSE, 'D'),
  ('AUS 4', 'Harry Souttar', 'Australia', 'AUS', 4, 'player', FALSE, 'D'),
  ('AUS 5', 'Alessandro Circati', 'Australia', 'AUS', 5, 'player', FALSE, 'D'),
  ('AUS 6', 'Jordan Bos', 'Australia', 'AUS', 6, 'player', FALSE, 'D'),
  ('AUS 7', 'Aziz Behich', 'Australia', 'AUS', 7, 'player', FALSE, 'D'),
  ('AUS 8', 'Cameron Burgess', 'Australia', 'AUS', 8, 'player', FALSE, 'D'),
  ('AUS 9', 'Lewis Miller', 'Australia', 'AUS', 9, 'player', FALSE, 'D'),
  ('AUS 10', 'Milos Degenek', 'Australia', 'AUS', 10, 'player', FALSE, 'D'),
  ('AUS 11', 'Jackson Irvine', 'Australia', 'AUS', 11, 'player', FALSE, 'D'),
  ('AUS 12', 'Riley McGree', 'Australia', 'AUS', 12, 'player', FALSE, 'D'),
  ('AUS 13', 'Team Photo', 'Australia', 'AUS', 13, 'team_photo', FALSE, 'D'),
  ('AUS 14', 'Aiden O''Neill', 'Australia', 'AUS', 14, 'player', FALSE, 'D'),
  ('AUS 15', 'Connor Metcalfe', 'Australia', 'AUS', 15, 'player', FALSE, 'D'),
  ('AUS 16', 'Patrick Yazbek', 'Australia', 'AUS', 16, 'player', FALSE, 'D'),
  ('AUS 17', 'Craig Goodwin', 'Australia', 'AUS', 17, 'player', FALSE, 'D'),
  ('AUS 18', 'Kusini Vengi', 'Australia', 'AUS', 18, 'player', FALSE, 'D'),
  ('AUS 19', 'Nestory Irankunda', 'Australia', 'AUS', 19, 'player', FALSE, 'D'),
  ('AUS 20', 'Mohamed Touré', 'Australia', 'AUS', 20, 'player', FALSE, 'D'),
  ('TUR 1', 'Team Logo', 'Türkiye', 'TUR', 1, 'team_logo', TRUE, 'D'),
  ('TUR 2', 'Ugurcan Cakir', 'Türkiye', 'TUR', 2, 'player', FALSE, 'D'),
  ('TUR 3', 'Mert Muldur', 'Türkiye', 'TUR', 3, 'player', FALSE, 'D'),
  ('TUR 4', 'Zeki Celik', 'Türkiye', 'TUR', 4, 'player', FALSE, 'D'),
  ('TUR 5', 'Abdulkerim Bardakci', 'Türkiye', 'TUR', 5, 'player', FALSE, 'D'),
  ('TUR 6', 'Caglar Soyuncu', 'Türkiye', 'TUR', 6, 'player', FALSE, 'D'),
  ('TUR 7', 'Merih Demiral', 'Türkiye', 'TUR', 7, 'player', FALSE, 'D'),
  ('TUR 8', 'Ferdi Kadioglu', 'Türkiye', 'TUR', 8, 'player', FALSE, 'D'),
  ('TUR 9', 'Kaan Ayhan', 'Türkiye', 'TUR', 9, 'player', FALSE, 'D'),
  ('TUR 10', 'Ismail Yuksek', 'Türkiye', 'TUR', 10, 'player', FALSE, 'D'),
  ('TUR 11', 'Hakan Calhanoglu', 'Türkiye', 'TUR', 11, 'player', FALSE, 'D'),
  ('TUR 12', 'Orkun Kokcu', 'Türkiye', 'TUR', 12, 'player', FALSE, 'D'),
  ('TUR 13', 'Team Photo', 'Türkiye', 'TUR', 13, 'team_photo', FALSE, 'D'),
  ('TUR 14', 'Arda Guler', 'Türkiye', 'TUR', 14, 'player', FALSE, 'D'),
  ('TUR 15', 'Irfan Can Kahveci', 'Türkiye', 'TUR', 15, 'player', FALSE, 'D'),
  ('TUR 16', 'Yunus Akgun', 'Türkiye', 'TUR', 16, 'player', FALSE, 'D'),
  ('TUR 17', 'Can Uzun', 'Türkiye', 'TUR', 17, 'player', FALSE, 'D'),
  ('TUR 18', 'Baris Alper Yilmaz', 'Türkiye', 'TUR', 18, 'player', FALSE, 'D'),
  ('TUR 19', 'Kerem Akturkoglu', 'Türkiye', 'TUR', 19, 'player', FALSE, 'D'),
  ('TUR 20', 'Kenan Yildiz', 'Türkiye', 'TUR', 20, 'player', FALSE, 'D'),
  ('GER 1', 'Team Logo', 'Germany', 'GER', 1, 'team_logo', TRUE, 'E'),
  ('GER 2', 'Marc-André ter Stegen', 'Germany', 'GER', 2, 'player', FALSE, 'E'),
  ('GER 3', 'Jonathan Tah', 'Germany', 'GER', 3, 'player', FALSE, 'E'),
  ('GER 4', 'David Raum', 'Germany', 'GER', 4, 'player', FALSE, 'E'),
  ('GER 5', 'Nico Schlotterbeck', 'Germany', 'GER', 5, 'player', FALSE, 'E'),
  ('GER 6', 'Antonio Rüdiger', 'Germany', 'GER', 6, 'player', FALSE, 'E'),
  ('GER 7', 'Waldemar Anton', 'Germany', 'GER', 7, 'player', FALSE, 'E'),
  ('GER 8', 'Ridle Baku', 'Germany', 'GER', 8, 'player', FALSE, 'E'),
  ('GER 9', 'Maximilian Mittelstadt', 'Germany', 'GER', 9, 'player', FALSE, 'E'),
  ('GER 10', 'Joshua Kimmich', 'Germany', 'GER', 10, 'player', FALSE, 'E'),
  ('GER 11', 'Florian Wirtz', 'Germany', 'GER', 11, 'player', FALSE, 'E'),
  ('GER 12', 'Felix Nmecha', 'Germany', 'GER', 12, 'player', FALSE, 'E'),
  ('GER 13', 'Team Photo', 'Germany', 'GER', 13, 'team_photo', FALSE, 'E'),
  ('GER 14', 'Leon Goretzka', 'Germany', 'GER', 14, 'player', FALSE, 'E'),
  ('GER 15', 'Jamal Musiala', 'Germany', 'GER', 15, 'player', FALSE, 'E'),
  ('GER 16', 'Serge Gnabry', 'Germany', 'GER', 16, 'player', FALSE, 'E'),
  ('GER 17', 'Kai Havertz', 'Germany', 'GER', 17, 'player', FALSE, 'E'),
  ('GER 18', 'Leroy Sane', 'Germany', 'GER', 18, 'player', FALSE, 'E'),
  ('GER 19', 'Karim Adeyemi', 'Germany', 'GER', 19, 'player', FALSE, 'E'),
  ('GER 20', 'Nick Woltemade', 'Germany', 'GER', 20, 'player', FALSE, 'E'),
  ('CUW 1', 'Team Logo', 'Curaçao', 'CUW', 1, 'team_logo', TRUE, 'E'),
  ('CUW 2', 'Eloy Room', 'Curaçao', 'CUW', 2, 'player', FALSE, 'E'),
  ('CUW 3', 'Armando Obispo', 'Curaçao', 'CUW', 3, 'player', FALSE, 'E'),
  ('CUW 4', 'Sherel Floranus', 'Curaçao', 'CUW', 4, 'player', FALSE, 'E'),
  ('CUW 5', 'Jurien Gaari', 'Curaçao', 'CUW', 5, 'player', FALSE, 'E'),
  ('CUW 6', 'Joshua Brenet', 'Curaçao', 'CUW', 6, 'player', FALSE, 'E'),
  ('CUW 7', 'Roshon Van Eijma', 'Curaçao', 'CUW', 7, 'player', FALSE, 'E'),
  ('CUW 8', 'Shurandy Sambo', 'Curaçao', 'CUW', 8, 'player', FALSE, 'E'),
  ('CUW 9', 'Livano Comenencia', 'Curaçao', 'CUW', 9, 'player', FALSE, 'E'),
  ('CUW 10', 'Godfried Roemeratoe', 'Curaçao', 'CUW', 10, 'player', FALSE, 'E'),
  ('CUW 11', 'Juninho Bacuna', 'Curaçao', 'CUW', 11, 'player', FALSE, 'E'),
  ('CUW 12', 'Leandro Bacuna', 'Curaçao', 'CUW', 12, 'player', FALSE, 'E'),
  ('CUW 13', 'Team Photo', 'Curaçao', 'CUW', 13, 'team_photo', FALSE, 'E'),
  ('CUW 14', 'Tahith Chong', 'Curaçao', 'CUW', 14, 'player', FALSE, 'E'),
  ('CUW 15', 'Kenji Gorre', 'Curaçao', 'CUW', 15, 'player', FALSE, 'E'),
  ('CUW 16', 'Jearl Margaritha', 'Curaçao', 'CUW', 16, 'player', FALSE, 'E'),
  ('CUW 17', 'Jurgen Locadia', 'Curaçao', 'CUW', 17, 'player', FALSE, 'E'),
  ('CUW 18', 'Jeremy Antonisse', 'Curaçao', 'CUW', 18, 'player', FALSE, 'E'),
  ('CUW 19', 'Gervane Kastaneer', 'Curaçao', 'CUW', 19, 'player', FALSE, 'E'),
  ('CUW 20', 'Sontje Hansen', 'Curaçao', 'CUW', 20, 'player', FALSE, 'E'),
  ('CIV 1', 'Team Logo', 'Ivory Coast', 'CIV', 1, 'team_logo', TRUE, 'E'),
  ('CIV 2', 'Yahia Fofana', 'Ivory Coast', 'CIV', 2, 'player', FALSE, 'E'),
  ('CIV 3', 'Ghislain Konan', 'Ivory Coast', 'CIV', 3, 'player', FALSE, 'E'),
  ('CIV 4', 'Wilfried Singo', 'Ivory Coast', 'CIV', 4, 'player', FALSE, 'E'),
  ('CIV 5', 'Odilon Kossounou', 'Ivory Coast', 'CIV', 5, 'player', FALSE, 'E'),
  ('CIV 6', 'Evan Ndicka', 'Ivory Coast', 'CIV', 6, 'player', FALSE, 'E'),
  ('CIV 7', 'Willy Boly', 'Ivory Coast', 'CIV', 7, 'player', FALSE, 'E'),
  ('CIV 8', 'Emmanuel Agbadou', 'Ivory Coast', 'CIV', 8, 'player', FALSE, 'E'),
  ('CIV 9', 'Ousmane Diomande', 'Ivory Coast', 'CIV', 9, 'player', FALSE, 'E'),
  ('CIV 10', 'Franck Kessie', 'Ivory Coast', 'CIV', 10, 'player', FALSE, 'E'),
  ('CIV 11', 'Seko Fofana', 'Ivory Coast', 'CIV', 11, 'player', FALSE, 'E'),
  ('CIV 12', 'Ibrahim Sangare', 'Ivory Coast', 'CIV', 12, 'player', FALSE, 'E'),
  ('CIV 13', 'Team Photo', 'Ivory Coast', 'CIV', 13, 'team_photo', FALSE, 'E'),
  ('CIV 14', 'Jean-Philippe Gbamin', 'Ivory Coast', 'CIV', 14, 'player', FALSE, 'E'),
  ('CIV 15', 'Amad Diallo', 'Ivory Coast', 'CIV', 15, 'player', FALSE, 'E'),
  ('CIV 16', 'Sébastien Haller', 'Ivory Coast', 'CIV', 16, 'player', FALSE, 'E'),
  ('CIV 17', 'Simon Adingra', 'Ivory Coast', 'CIV', 17, 'player', FALSE, 'E'),
  ('CIV 18', 'Yan Diomande', 'Ivory Coast', 'CIV', 18, 'player', FALSE, 'E'),
  ('CIV 19', 'Evann Guessand', 'Ivory Coast', 'CIV', 19, 'player', FALSE, 'E'),
  ('CIV 20', 'Oumar Diakite', 'Ivory Coast', 'CIV', 20, 'player', FALSE, 'E'),
  ('ECU 1', 'Team Logo', 'Ecuador', 'ECU', 1, 'team_logo', TRUE, 'E'),
  ('ECU 2', 'Hernán Galíndez', 'Ecuador', 'ECU', 2, 'player', FALSE, 'E'),
  ('ECU 3', 'Gonzalo Valle', 'Ecuador', 'ECU', 3, 'player', FALSE, 'E'),
  ('ECU 4', 'Piero Hincapié', 'Ecuador', 'ECU', 4, 'player', FALSE, 'E'),
  ('ECU 5', 'Pervis Estupiñán', 'Ecuador', 'ECU', 5, 'player', FALSE, 'E'),
  ('ECU 6', 'Willian Pacho', 'Ecuador', 'ECU', 6, 'player', FALSE, 'E'),
  ('ECU 7', 'Ángelo Preciado', 'Ecuador', 'ECU', 7, 'player', FALSE, 'E'),
  ('ECU 8', 'Joel Ordóñez', 'Ecuador', 'ECU', 8, 'player', FALSE, 'E'),
  ('ECU 9', 'Moises Caicedo', 'Ecuador', 'ECU', 9, 'player', FALSE, 'E'),
  ('ECU 10', 'Alan Franco', 'Ecuador', 'ECU', 10, 'player', FALSE, 'E'),
  ('ECU 11', 'Kendry Paez', 'Ecuador', 'ECU', 11, 'player', FALSE, 'E'),
  ('ECU 12', 'Pedro Vite', 'Ecuador', 'ECU', 12, 'player', FALSE, 'E'),
  ('ECU 13', 'Team Photo', 'Ecuador', 'ECU', 13, 'team_photo', FALSE, 'E'),
  ('ECU 14', 'John Veboah', 'Ecuador', 'ECU', 14, 'player', FALSE, 'E'),
  ('ECU 15', 'Leonardo Campana', 'Ecuador', 'ECU', 15, 'player', FALSE, 'E'),
  ('ECU 16', 'Gonzalo Plata', 'Ecuador', 'ECU', 16, 'player', FALSE, 'E'),
  ('ECU 17', 'Nilson Angulo', 'Ecuador', 'ECU', 17, 'player', FALSE, 'E'),
  ('ECU 18', 'Alan Minda', 'Ecuador', 'ECU', 18, 'player', FALSE, 'E'),
  ('ECU 19', 'Kevin Rodriguez', 'Ecuador', 'ECU', 19, 'player', FALSE, 'E'),
  ('ECU 20', 'Enner Valencia', 'Ecuador', 'ECU', 20, 'player', FALSE, 'E'),
  ('NED 1', 'Team Logo', 'Netherlands', 'NED', 1, 'team_logo', TRUE, 'F'),
  ('NED 2', 'Bart Verbruggen', 'Netherlands', 'NED', 2, 'player', FALSE, 'F'),
  ('NED 3', 'Virgil van Dijk', 'Netherlands', 'NED', 3, 'player', FALSE, 'F'),
  ('NED 4', 'Micky van de Ven', 'Netherlands', 'NED', 4, 'player', FALSE, 'F'),
  ('NED 5', 'Jurrien Timber', 'Netherlands', 'NED', 5, 'player', FALSE, 'F'),
  ('NED 6', 'Denzel Dumfries', 'Netherlands', 'NED', 6, 'player', FALSE, 'F'),
  ('NED 7', 'Nathan Aké', 'Netherlands', 'NED', 7, 'player', FALSE, 'F'),
  ('NED 8', 'Jeremie Frimpong', 'Netherlands', 'NED', 8, 'player', FALSE, 'F'),
  ('NED 9', 'Jan Paul van Hecke', 'Netherlands', 'NED', 9, 'player', FALSE, 'F'),
  ('NED 10', 'Tijjani Reijnders', 'Netherlands', 'NED', 10, 'player', FALSE, 'F'),
  ('NED 11', 'Ryan Gravenberch', 'Netherlands', 'NED', 11, 'player', FALSE, 'F'),
  ('NED 12', 'Teun Koopmeiners', 'Netherlands', 'NED', 12, 'player', FALSE, 'F'),
  ('NED 13', 'Team Photo', 'Netherlands', 'NED', 13, 'team_photo', FALSE, 'F'),
  ('NED 14', 'Frenkie de Jong', 'Netherlands', 'NED', 14, 'player', FALSE, 'F'),
  ('NED 15', 'Xavi Simons', 'Netherlands', 'NED', 15, 'player', FALSE, 'F'),
  ('NED 16', 'Justin Kluivert', 'Netherlands', 'NED', 16, 'player', FALSE, 'F'),
  ('NED 17', 'Memphis Depay', 'Netherlands', 'NED', 17, 'player', FALSE, 'F'),
  ('NED 18', 'Donyell Malen', 'Netherlands', 'NED', 18, 'player', FALSE, 'F'),
  ('NED 19', 'Wout Weghorst', 'Netherlands', 'NED', 19, 'player', FALSE, 'F'),
  ('NED 20', 'Cody Gakpo', 'Netherlands', 'NED', 20, 'player', FALSE, 'F'),
  ('JPN 1', 'Team Logo', 'Japan', 'JPN', 1, 'team_logo', TRUE, 'F'),
  ('JPN 2', 'Zion Suzuki', 'Japan', 'JPN', 2, 'player', FALSE, 'F'),
  ('JPN 3', 'Henry Heroki Mochizuki', 'Japan', 'JPN', 3, 'player', FALSE, 'F'),
  ('JPN 4', 'Ayumu Seko', 'Japan', 'JPN', 4, 'player', FALSE, 'F'),
  ('JPN 5', 'Junnosuke Suzuki', 'Japan', 'JPN', 5, 'player', FALSE, 'F'),
  ('JPN 6', 'Shogo Taniguchi', 'Japan', 'JPN', 6, 'player', FALSE, 'F'),
  ('JPN 7', 'Tsuyoshi Watanabe', 'Japan', 'JPN', 7, 'player', FALSE, 'F'),
  ('JPN 8', 'Kaishu Sano', 'Japan', 'JPN', 8, 'player', FALSE, 'F'),
  ('JPN 9', 'Yuki Soma', 'Japan', 'JPN', 9, 'player', FALSE, 'F'),
  ('JPN 10', 'Ao Tanaka', 'Japan', 'JPN', 10, 'player', FALSE, 'F'),
  ('JPN 11', 'Daichi Kamada', 'Japan', 'JPN', 11, 'player', FALSE, 'F'),
  ('JPN 12', 'Takefusa Kubo', 'Japan', 'JPN', 12, 'player', FALSE, 'F'),
  ('JPN 13', 'Team Photo', 'Japan', 'JPN', 13, 'team_photo', FALSE, 'F'),
  ('JPN 14', 'Ritsu Doan', 'Japan', 'JPN', 14, 'player', FALSE, 'F'),
  ('JPN 15', 'Keito Nakamura', 'Japan', 'JPN', 15, 'player', FALSE, 'F'),
  ('JPN 16', 'Takumi Minamino', 'Japan', 'JPN', 16, 'player', FALSE, 'F'),
  ('JPN 17', 'Shuto Machino', 'Japan', 'JPN', 17, 'player', FALSE, 'F'),
  ('JPN 18', 'Junya Ito', 'Japan', 'JPN', 18, 'player', FALSE, 'F'),
  ('JPN 19', 'Koki Ogawa', 'Japan', 'JPN', 19, 'player', FALSE, 'F'),
  ('JPN 20', 'Ayase Ueda', 'Japan', 'JPN', 20, 'player', FALSE, 'F'),
  ('SWE 1', 'Team Logo', 'Sweden', 'SWE', 1, 'team_logo', TRUE, 'F'),
  ('SWE 2', 'Victor Johansson', 'Sweden', 'SWE', 2, 'player', FALSE, 'F'),
  ('SWE 3', 'Isak Hien', 'Sweden', 'SWE', 3, 'player', FALSE, 'F'),
  ('SWE 4', 'Gabriel Gudmundsson', 'Sweden', 'SWE', 4, 'player', FALSE, 'F'),
  ('SWE 5', 'Emil Holm', 'Sweden', 'SWE', 5, 'player', FALSE, 'F'),
  ('SWE 6', 'Victor Nilsson Lindelöf', 'Sweden', 'SWE', 6, 'player', FALSE, 'F'),
  ('SWE 7', 'Gustaf Lagerbielke', 'Sweden', 'SWE', 7, 'player', FALSE, 'F'),
  ('SWE 8', 'Lucas Bergvall', 'Sweden', 'SWE', 8, 'player', FALSE, 'F'),
  ('SWE 9', 'Hugo Larsson', 'Sweden', 'SWE', 9, 'player', FALSE, 'F'),
  ('SWE 10', 'Jesper Karlström', 'Sweden', 'SWE', 10, 'player', FALSE, 'F'),
  ('SWE 11', 'Yasin Ayari', 'Sweden', 'SWE', 11, 'player', FALSE, 'F'),
  ('SWE 12', 'Mattias Svanberg', 'Sweden', 'SWE', 12, 'player', FALSE, 'F'),
  ('SWE 13', 'Team Photo', 'Sweden', 'SWE', 13, 'team_photo', FALSE, 'F'),
  ('SWE 14', 'Daniel Svensson', 'Sweden', 'SWE', 14, 'player', FALSE, 'F'),
  ('SWE 15', 'Ken Sema', 'Sweden', 'SWE', 15, 'player', FALSE, 'F'),
  ('SWE 16', 'Roony Bardghji', 'Sweden', 'SWE', 16, 'player', FALSE, 'F'),
  ('SWE 17', 'Dejan Kulusevski', 'Sweden', 'SWE', 17, 'player', FALSE, 'F'),
  ('SWE 18', 'Anthony Elanga', 'Sweden', 'SWE', 18, 'player', FALSE, 'F'),
  ('SWE 19', 'Alexander Isak', 'Sweden', 'SWE', 19, 'player', FALSE, 'F'),
  ('SWE 20', 'Viktor Gyökeres', 'Sweden', 'SWE', 20, 'player', FALSE, 'F'),
  ('TUN 1', 'Team Logo', 'Tunisia', 'TUN', 1, 'team_logo', TRUE, 'F'),
  ('TUN 2', 'Bechir Ben Said', 'Tunisia', 'TUN', 2, 'player', FALSE, 'F'),
  ('TUN 3', 'Aymen Dahmen', 'Tunisia', 'TUN', 3, 'player', FALSE, 'F'),
  ('TUN 4', 'Yan Valery', 'Tunisia', 'TUN', 4, 'player', FALSE, 'F'),
  ('TUN 5', 'Montassar Talbi', 'Tunisia', 'TUN', 5, 'player', FALSE, 'F'),
  ('TUN 6', 'Yassine Meriah', 'Tunisia', 'TUN', 6, 'player', FALSE, 'F'),
  ('TUN 7', 'Ali Abdi', 'Tunisia', 'TUN', 7, 'player', FALSE, 'F'),
  ('TUN 8', 'Dylan Bronn', 'Tunisia', 'TUN', 8, 'player', FALSE, 'F'),
  ('TUN 9', 'Ellyes Skhiri', 'Tunisia', 'TUN', 9, 'player', FALSE, 'F'),
  ('TUN 10', 'Aissa Laidouni', 'Tunisia', 'TUN', 10, 'player', FALSE, 'F'),
  ('TUN 11', 'Ferjani Sassi', 'Tunisia', 'TUN', 11, 'player', FALSE, 'F'),
  ('TUN 12', 'Mohamed Ali Ben Romdhane', 'Tunisia', 'TUN', 12, 'player', FALSE, 'F'),
  ('TUN 13', 'Team Photo', 'Tunisia', 'TUN', 13, 'team_photo', FALSE, 'F'),
  ('TUN 14', 'Hannibal Mejbri', 'Tunisia', 'TUN', 14, 'player', FALSE, 'F'),
  ('TUN 15', 'Elias Achouri', 'Tunisia', 'TUN', 15, 'player', FALSE, 'F'),
  ('TUN 16', 'Elias Saad', 'Tunisia', 'TUN', 16, 'player', FALSE, 'F'),
  ('TUN 17', 'Hazem Mastouri', 'Tunisia', 'TUN', 17, 'player', FALSE, 'F'),
  ('TUN 18', 'Ismael Gharbi', 'Tunisia', 'TUN', 18, 'player', FALSE, 'F'),
  ('TUN 19', 'Sayfallah Ltaief', 'Tunisia', 'TUN', 19, 'player', FALSE, 'F'),
  ('TUN 20', 'Naim Sliti', 'Tunisia', 'TUN', 20, 'player', FALSE, 'F'),
  ('BEL 1', 'Team Logo', 'Belgium', 'BEL', 1, 'team_logo', TRUE, 'G'),
  ('BEL 2', 'Thibaut Courtois', 'Belgium', 'BEL', 2, 'player', FALSE, 'G'),
  ('BEL 3', 'Arthur Theate', 'Belgium', 'BEL', 3, 'player', FALSE, 'G'),
  ('BEL 4', 'Timothy Castagne', 'Belgium', 'BEL', 4, 'player', FALSE, 'G'),
  ('BEL 5', 'Zeno Debast', 'Belgium', 'BEL', 5, 'player', FALSE, 'G'),
  ('BEL 6', 'Brandon Mechele', 'Belgium', 'BEL', 6, 'player', FALSE, 'G'),
  ('BEL 7', 'Maxim De Cuyper', 'Belgium', 'BEL', 7, 'player', FALSE, 'G'),
  ('BEL 8', 'Thomas Meunier', 'Belgium', 'BEL', 8, 'player', FALSE, 'G'),
  ('BEL 9', 'Youri Tielemans', 'Belgium', 'BEL', 9, 'player', FALSE, 'G'),
  ('BEL 10', 'Amadou Onana', 'Belgium', 'BEL', 10, 'player', FALSE, 'G'),
  ('BEL 11', 'Nicolas Raskin', 'Belgium', 'BEL', 11, 'player', FALSE, 'G'),
  ('BEL 12', 'Alexis Saelemaekers', 'Belgium', 'BEL', 12, 'player', FALSE, 'G'),
  ('BEL 13', 'Team Photo', 'Belgium', 'BEL', 13, 'team_photo', FALSE, 'G'),
  ('BEL 14', 'Hans Vanaken', 'Belgium', 'BEL', 14, 'player', FALSE, 'G'),
  ('BEL 15', 'Kevin De Bruyne', 'Belgium', 'BEL', 15, 'player', FALSE, 'G'),
  ('BEL 16', 'Jérémy Doku', 'Belgium', 'BEL', 16, 'player', FALSE, 'G'),
  ('BEL 17', 'Charles De Ketelaere', 'Belgium', 'BEL', 17, 'player', FALSE, 'G'),
  ('BEL 18', 'Leandro Trossard', 'Belgium', 'BEL', 18, 'player', FALSE, 'G'),
  ('BEL 19', 'Loïs Openda', 'Belgium', 'BEL', 19, 'player', FALSE, 'G'),
  ('BEL 20', 'Romelu Lukaku', 'Belgium', 'BEL', 20, 'player', FALSE, 'G'),
  ('EGY 1', 'Team Logo', 'Egypt', 'EGY', 1, 'team_logo', TRUE, 'G'),
  ('EGY 2', 'Mohamed El Shenawy', 'Egypt', 'EGY', 2, 'player', FALSE, 'G'),
  ('EGY 3', 'Mohamed Hany', 'Egypt', 'EGY', 3, 'player', FALSE, 'G'),
  ('EGY 4', 'Mohamed Hamdy', 'Egypt', 'EGY', 4, 'player', FALSE, 'G'),
  ('EGY 5', 'Yasser Ibrahim', 'Egypt', 'EGY', 5, 'player', FALSE, 'G'),
  ('EGY 6', 'Khaled Sobhi', 'Egypt', 'EGY', 6, 'player', FALSE, 'G'),
  ('EGY 7', 'Ramy Rabia', 'Egypt', 'EGY', 7, 'player', FALSE, 'G'),
  ('EGY 8', 'Hossam Abdelmaguid', 'Egypt', 'EGY', 8, 'player', FALSE, 'G'),
  ('EGY 9', 'Ahmed Fatouh', 'Egypt', 'EGY', 9, 'player', FALSE, 'G'),
  ('EGY 10', 'Marwan Attia', 'Egypt', 'EGY', 10, 'player', FALSE, 'G'),
  ('EGY 11', 'Zizo', 'Egypt', 'EGY', 11, 'player', FALSE, 'G'),
  ('EGY 12', 'Hamdy Fathy', 'Egypt', 'EGY', 12, 'player', FALSE, 'G'),
  ('EGY 13', 'Team Photo', 'Egypt', 'EGY', 13, 'team_photo', FALSE, 'G'),
  ('EGY 14', 'Mohamed Lasheen', 'Egypt', 'EGY', 14, 'player', FALSE, 'G'),
  ('EGY 15', 'Emam Ashour', 'Egypt', 'EGY', 15, 'player', FALSE, 'G'),
  ('EGY 16', 'Osama Faisal', 'Egypt', 'EGY', 16, 'player', FALSE, 'G'),
  ('EGY 17', 'Mohamed Salah', 'Egypt', 'EGY', 17, 'player', FALSE, 'G'),
  ('EGY 18', 'Mostafa Mohamed', 'Egypt', 'EGY', 18, 'player', FALSE, 'G'),
  ('EGY 19', 'Trezeguet', 'Egypt', 'EGY', 19, 'player', FALSE, 'G'),
  ('EGY 20', 'Omar Marmoush', 'Egypt', 'EGY', 20, 'player', FALSE, 'G'),
  ('IRN 1', 'Team Logo', 'Iran', 'IRN', 1, 'team_logo', TRUE, 'G'),
  ('IRN 2', 'Alireza Beiranvand', 'Iran', 'IRN', 2, 'player', FALSE, 'G'),
  ('IRN 3', 'Morteza Pouraliganji', 'Iran', 'IRN', 3, 'player', FALSE, 'G'),
  ('IRN 4', 'Ehsan Hajsafi', 'Iran', 'IRN', 4, 'player', FALSE, 'G'),
  ('IRN 5', 'Milad Mohammadi', 'Iran', 'IRN', 5, 'player', FALSE, 'G'),
  ('IRN 6', 'Shojae Khalilzadeh', 'Iran', 'IRN', 6, 'player', FALSE, 'G'),
  ('IRN 7', 'Ramin Rezaeian', 'Iran', 'IRN', 7, 'player', FALSE, 'G'),
  ('IRN 8', 'Hossein Kanaani', 'Iran', 'IRN', 8, 'player', FALSE, 'G'),
  ('IRN 9', 'Sadegh Moharrami', 'Iran', 'IRN', 9, 'player', FALSE, 'G'),
  ('IRN 10', 'Saleh Hardani', 'Iran', 'IRN', 10, 'player', FALSE, 'G'),
  ('IRN 11', 'Saeed Ezatolahi', 'Iran', 'IRN', 11, 'player', FALSE, 'G'),
  ('IRN 12', 'Saman Ghoddos', 'Iran', 'IRN', 12, 'player', FALSE, 'G'),
  ('IRN 13', 'Team Photo', 'Iran', 'IRN', 13, 'team_photo', FALSE, 'G'),
  ('IRN 14', 'Omid Noorafkan', 'Iran', 'IRN', 14, 'player', FALSE, 'G'),
  ('IRN 15', 'Roozbeh Cheshmi', 'Iran', 'IRN', 15, 'player', FALSE, 'G'),
  ('IRN 16', 'Mohammad Mohebi', 'Iran', 'IRN', 16, 'player', FALSE, 'G'),
  ('IRN 17', 'Sardar Azmoun', 'Iran', 'IRN', 17, 'player', FALSE, 'G'),
  ('IRN 18', 'Mehdi Taremi', 'Iran', 'IRN', 18, 'player', FALSE, 'G'),
  ('IRN 19', 'Alireza Jahanbakhsh', 'Iran', 'IRN', 19, 'player', FALSE, 'G'),
  ('IRN 20', 'Ali Gholizadeh', 'Iran', 'IRN', 20, 'player', FALSE, 'G'),
  ('NZL 1', 'Team Logo', 'New Zealand', 'NZL', 1, 'team_logo', TRUE, 'G'),
  ('NZL 2', 'Max Crocombe Payne', 'New Zealand', 'NZL', 2, 'player', FALSE, 'G'),
  ('NZL 3', 'Alex Paulsen', 'New Zealand', 'NZL', 3, 'player', FALSE, 'G'),
  ('NZL 4', 'Michael Boxall', 'New Zealand', 'NZL', 4, 'player', FALSE, 'G'),
  ('NZL 5', 'Liberato Cacace', 'New Zealand', 'NZL', 5, 'player', FALSE, 'G'),
  ('NZL 6', 'Tim Payne', 'New Zealand', 'NZL', 6, 'player', FALSE, 'G'),
  ('NZL 7', 'Tyler Bindon', 'New Zealand', 'NZL', 7, 'player', FALSE, 'G'),
  ('NZL 8', 'Francis de Vries', 'New Zealand', 'NZL', 8, 'player', FALSE, 'G'),
  ('NZL 9', 'Finn Surman', 'New Zealand', 'NZL', 9, 'player', FALSE, 'G'),
  ('NZL 10', 'Joe Bell', 'New Zealand', 'NZL', 10, 'player', FALSE, 'G'),
  ('NZL 11', 'Sarpreet Singh', 'New Zealand', 'NZL', 11, 'player', FALSE, 'G'),
  ('NZL 12', 'Ryan Thomas', 'New Zealand', 'NZL', 12, 'player', FALSE, 'G'),
  ('NZL 13', 'Team Photo', 'New Zealand', 'NZL', 13, 'team_photo', FALSE, 'G'),
  ('NZL 14', 'Matthew Garbett', 'New Zealand', 'NZL', 14, 'player', FALSE, 'G'),
  ('NZL 15', 'Marko Stamenić', 'New Zealand', 'NZL', 15, 'player', FALSE, 'G'),
  ('NZL 16', 'Ben Old', 'New Zealand', 'NZL', 16, 'player', FALSE, 'G'),
  ('NZL 17', 'Chris Wood', 'New Zealand', 'NZL', 17, 'player', FALSE, 'G'),
  ('NZL 18', 'Elijah Just', 'New Zealand', 'NZL', 18, 'player', FALSE, 'G'),
  ('NZL 19', 'Callum McCowatt', 'New Zealand', 'NZL', 19, 'player', FALSE, 'G'),
  ('NZL 20', 'Kosta Barbarouses', 'New Zealand', 'NZL', 20, 'player', FALSE, 'G'),
  ('ESP 1', 'Team Logo', 'Spain', 'ESP', 1, 'team_logo', TRUE, 'H'),
  ('ESP 2', 'Unai Simon', 'Spain', 'ESP', 2, 'player', FALSE, 'H'),
  ('ESP 3', 'Robin Le Normand', 'Spain', 'ESP', 3, 'player', FALSE, 'H'),
  ('ESP 4', 'Aymeric Laporte', 'Spain', 'ESP', 4, 'player', FALSE, 'H'),
  ('ESP 5', 'Dean Huijsen', 'Spain', 'ESP', 5, 'player', FALSE, 'H'),
  ('ESP 6', 'Pedro Porro', 'Spain', 'ESP', 6, 'player', FALSE, 'H'),
  ('ESP 7', 'Dani Carvajal', 'Spain', 'ESP', 7, 'player', FALSE, 'H'),
  ('ESP 8', 'Marc Cucurella', 'Spain', 'ESP', 8, 'player', FALSE, 'H'),
  ('ESP 9', 'Martín Zubimendi', 'Spain', 'ESP', 9, 'player', FALSE, 'H'),
  ('ESP 10', 'Rodri', 'Spain', 'ESP', 10, 'player', FALSE, 'H'),
  ('ESP 11', 'Pedri', 'Spain', 'ESP', 11, 'player', FALSE, 'H'),
  ('ESP 12', 'Fabian Ruiz', 'Spain', 'ESP', 12, 'player', FALSE, 'H'),
  ('ESP 13', 'Team Photo', 'Spain', 'ESP', 13, 'team_photo', FALSE, 'H'),
  ('ESP 14', 'Mikel Merino', 'Spain', 'ESP', 14, 'player', FALSE, 'H'),
  ('ESP 15', 'Lamine Yamal', 'Spain', 'ESP', 15, 'player', FALSE, 'H'),
  ('ESP 16', 'Dani Olmo', 'Spain', 'ESP', 16, 'player', FALSE, 'H'),
  ('ESP 17', 'Nico Williams', 'Spain', 'ESP', 17, 'player', FALSE, 'H'),
  ('ESP 18', 'Ferran Torres', 'Spain', 'ESP', 18, 'player', FALSE, 'H'),
  ('ESP 19', 'Álvaro Morata', 'Spain', 'ESP', 19, 'player', FALSE, 'H'),
  ('ESP 20', 'Mikel Oyarzabal', 'Spain', 'ESP', 20, 'player', FALSE, 'H'),
  ('CPV 1', 'Team Logo', 'Cape Verde', 'CPV', 1, 'team_logo', TRUE, 'H'),
  ('CPV 2', 'Vozinha', 'Cape Verde', 'CPV', 2, 'player', FALSE, 'H'),
  ('CPV 3', 'Logan Costa', 'Cape Verde', 'CPV', 3, 'player', FALSE, 'H'),
  ('CPV 4', 'Pico', 'Cape Verde', 'CPV', 4, 'player', FALSE, 'H'),
  ('CPV 5', 'Diney', 'Cape Verde', 'CPV', 5, 'player', FALSE, 'H'),
  ('CPV 6', 'Steven Moreira', 'Cape Verde', 'CPV', 6, 'player', FALSE, 'H'),
  ('CPV 7', 'Wagner Pina', 'Cape Verde', 'CPV', 7, 'player', FALSE, 'H'),
  ('CPV 8', 'Joao Paulo', 'Cape Verde', 'CPV', 8, 'player', FALSE, 'H'),
  ('CPV 9', 'Yannick Semedo', 'Cape Verde', 'CPV', 9, 'player', FALSE, 'H'),
  ('CPV 10', 'Kevin Pina', 'Cape Verde', 'CPV', 10, 'player', FALSE, 'H'),
  ('CPV 11', 'Patrick Andrade', 'Cape Verde', 'CPV', 11, 'player', FALSE, 'H'),
  ('CPV 12', 'Jamiro Monteiro', 'Cape Verde', 'CPV', 12, 'player', FALSE, 'H'),
  ('CPV 13', 'Team Photo', 'Cape Verde', 'CPV', 13, 'team_photo', FALSE, 'H'),
  ('CPV 14', 'Deroy Duarte', 'Cape Verde', 'CPV', 14, 'player', FALSE, 'H'),
  ('CPV 15', 'Garry Rodrigues', 'Cape Verde', 'CPV', 15, 'player', FALSE, 'H'),
  ('CPV 16', 'Jovane Cabral', 'Cape Verde', 'CPV', 16, 'player', FALSE, 'H'),
  ('CPV 17', 'Ryan Mendes', 'Cape Verde', 'CPV', 17, 'player', FALSE, 'H'),
  ('CPV 18', 'Dailon Livramento', 'Cape Verde', 'CPV', 18, 'player', FALSE, 'H'),
  ('CPV 19', 'Willy Semedo', 'Cape Verde', 'CPV', 19, 'player', FALSE, 'H'),
  ('CPV 20', 'Bebe', 'Cape Verde', 'CPV', 20, 'player', FALSE, 'H'),
  ('KSA 1', 'Team Logo', 'Saudi Arabia', 'KSA', 1, 'team_logo', TRUE, 'H'),
  ('KSA 2', 'Nawaf Alaqidi', 'Saudi Arabia', 'KSA', 2, 'player', FALSE, 'H'),
  ('KSA 3', 'Abdulrahman Al-Sanbi', 'Saudi Arabia', 'KSA', 3, 'player', FALSE, 'H'),
  ('KSA 4', 'Saud Abdulhamid', 'Saudi Arabia', 'KSA', 4, 'player', FALSE, 'H'),
  ('KSA 5', 'Nawaf Bouwashl', 'Saudi Arabia', 'KSA', 5, 'player', FALSE, 'H'),
  ('KSA 6', 'Jihad Thakri', 'Saudi Arabia', 'KSA', 6, 'player', FALSE, 'H'),
  ('KSA 7', 'Moteb Al-Harbi', 'Saudi Arabia', 'KSA', 7, 'player', FALSE, 'H'),
  ('KSA 8', 'Hassan Altambakti', 'Saudi Arabia', 'KSA', 8, 'player', FALSE, 'H'),
  ('KSA 9', 'Musab Aljuwayr', 'Saudi Arabia', 'KSA', 9, 'player', FALSE, 'H'),
  ('KSA 10', 'Ziyad Aljohani', 'Saudi Arabia', 'KSA', 10, 'player', FALSE, 'H'),
  ('KSA 11', 'Abdullah Alkhaibari', 'Saudi Arabia', 'KSA', 11, 'player', FALSE, 'H'),
  ('KSA 12', 'Nasser Aldawsari', 'Saudi Arabia', 'KSA', 12, 'player', FALSE, 'H'),
  ('KSA 13', 'Team Photo', 'Saudi Arabia', 'KSA', 13, 'team_photo', FALSE, 'H'),
  ('KSA 14', 'Saleh Abu Alshamat', 'Saudi Arabia', 'KSA', 14, 'player', FALSE, 'H'),
  ('KSA 15', 'Marwan Alsahafi', 'Saudi Arabia', 'KSA', 15, 'player', FALSE, 'H'),
  ('KSA 16', 'Salem Aldawsari', 'Saudi Arabia', 'KSA', 16, 'player', FALSE, 'H'),
  ('KSA 17', 'Abdulrahman Al-Aboud', 'Saudi Arabia', 'KSA', 17, 'player', FALSE, 'H'),
  ('KSA 18', 'Feras Akbrikan', 'Saudi Arabia', 'KSA', 18, 'player', FALSE, 'H'),
  ('KSA 19', 'Saleh Alshehri', 'Saudi Arabia', 'KSA', 19, 'player', FALSE, 'H'),
  ('KSA 20', 'Abdullah Al-Hamdan', 'Saudi Arabia', 'KSA', 20, 'player', FALSE, 'H'),
  ('URU 1', 'Team Logo', 'Uruguay', 'URU', 1, 'team_logo', TRUE, 'H'),
  ('URU 2', 'Sergio Rochet', 'Uruguay', 'URU', 2, 'player', FALSE, 'H'),
  ('URU 3', 'Santiago Mele', 'Uruguay', 'URU', 3, 'player', FALSE, 'H'),
  ('URU 4', 'Ronald Araujo', 'Uruguay', 'URU', 4, 'player', FALSE, 'H'),
  ('URU 5', 'José María Giménez', 'Uruguay', 'URU', 5, 'player', FALSE, 'H'),
  ('URU 6', 'Sebastian Caceres', 'Uruguay', 'URU', 6, 'player', FALSE, 'H'),
  ('URU 7', 'Mathias Olivera', 'Uruguay', 'URU', 7, 'player', FALSE, 'H'),
  ('URU 8', 'Guillermo Varela', 'Uruguay', 'URU', 8, 'player', FALSE, 'H'),
  ('URU 9', 'Nahitan Nandez', 'Uruguay', 'URU', 9, 'player', FALSE, 'H'),
  ('URU 10', 'Federico Valverde', 'Uruguay', 'URU', 10, 'player', FALSE, 'H'),
  ('URU 11', 'Giorgian De Arrascaeta', 'Uruguay', 'URU', 11, 'player', FALSE, 'H'),
  ('URU 12', 'Rodrigo Bentancur', 'Uruguay', 'URU', 12, 'player', FALSE, 'H'),
  ('URU 13', 'Team Photo', 'Uruguay', 'URU', 13, 'team_photo', FALSE, 'H'),
  ('URU 14', 'Manuel Ugarte', 'Uruguay', 'URU', 14, 'player', FALSE, 'H'),
  ('URU 15', 'Nicolás de la Cruz', 'Uruguay', 'URU', 15, 'player', FALSE, 'H'),
  ('URU 16', 'Maxi Araujo', 'Uruguay', 'URU', 16, 'player', FALSE, 'H'),
  ('URU 17', 'Darwin Núñez', 'Uruguay', 'URU', 17, 'player', FALSE, 'H'),
  ('URU 18', 'Federico Viñas', 'Uruguay', 'URU', 18, 'player', FALSE, 'H'),
  ('URU 19', 'Rodrigo Aguirre', 'Uruguay', 'URU', 19, 'player', FALSE, 'H'),
  ('URU 20', 'Facundo Pellistri', 'Uruguay', 'URU', 20, 'player', FALSE, 'H'),
  ('FRA 1', 'Team Logo', 'France', 'FRA', 1, 'team_logo', TRUE, 'I'),
  ('FRA 2', 'Mike Maignan', 'France', 'FRA', 2, 'player', FALSE, 'I'),
  ('FRA 3', 'Theo Hernandez', 'France', 'FRA', 3, 'player', FALSE, 'I'),
  ('FRA 4', 'William Saliba', 'France', 'FRA', 4, 'player', FALSE, 'I'),
  ('FRA 5', 'Jules Kounde', 'France', 'FRA', 5, 'player', FALSE, 'I'),
  ('FRA 6', 'Ibrahima Konate', 'France', 'FRA', 6, 'player', FALSE, 'I'),
  ('FRA 7', 'Dayot Upamecano', 'France', 'FRA', 7, 'player', FALSE, 'I'),
  ('FRA 8', 'Lucas Digne', 'France', 'FRA', 8, 'player', FALSE, 'I'),
  ('FRA 9', 'Aurélien Tchouaméni', 'France', 'FRA', 9, 'player', FALSE, 'I'),
  ('FRA 10', 'Eduardo Camavinga', 'France', 'FRA', 10, 'player', FALSE, 'I'),
  ('FRA 11', 'Manu Kone', 'France', 'FRA', 11, 'player', FALSE, 'I'),
  ('FRA 12', 'Adrien Rabiot', 'France', 'FRA', 12, 'player', FALSE, 'I'),
  ('FRA 13', 'Team Photo', 'France', 'FRA', 13, 'team_photo', FALSE, 'I'),
  ('FRA 14', 'Michael Olise', 'France', 'FRA', 14, 'player', FALSE, 'I'),
  ('FRA 15', 'Ousmane Dembele', 'France', 'FRA', 15, 'player', FALSE, 'I'),
  ('FRA 16', 'Bradley Barcola', 'France', 'FRA', 16, 'player', FALSE, 'I'),
  ('FRA 17', 'Désiré Doué', 'France', 'FRA', 17, 'player', FALSE, 'I'),
  ('FRA 18', 'Kingsley Coman', 'France', 'FRA', 18, 'player', FALSE, 'I'),
  ('FRA 19', 'Hugo Ekitike', 'France', 'FRA', 19, 'player', FALSE, 'I'),
  ('FRA 20', 'Kylian Mbappe', 'France', 'FRA', 20, 'player', FALSE, 'I'),
  ('SEN 1', 'Team Logo', 'Senegal', 'SEN', 1, 'team_logo', TRUE, 'I'),
  ('SEN 2', 'Edouard Mendy', 'Senegal', 'SEN', 2, 'player', FALSE, 'I'),
  ('SEN 3', 'Yehvann Diouf', 'Senegal', 'SEN', 3, 'player', FALSE, 'I'),
  ('SEN 4', 'Moussa Niakhaté', 'Senegal', 'SEN', 4, 'player', FALSE, 'I'),
  ('SEN 5', 'Abdoulaye Seck', 'Senegal', 'SEN', 5, 'player', FALSE, 'I'),
  ('SEN 6', 'Ismail Jakobs', 'Senegal', 'SEN', 6, 'player', FALSE, 'I'),
  ('SEN 7', 'El Hadji Malick Diouf', 'Senegal', 'SEN', 7, 'player', FALSE, 'I'),
  ('SEN 8', 'Kalidou Koulibaly', 'Senegal', 'SEN', 8, 'player', FALSE, 'I'),
  ('SEN 9', 'Idrissa Gana Gueye', 'Senegal', 'SEN', 9, 'player', FALSE, 'I'),
  ('SEN 10', 'Pape Matar Sarr', 'Senegal', 'SEN', 10, 'player', FALSE, 'I'),
  ('SEN 11', 'Pape Gueye', 'Senegal', 'SEN', 11, 'player', FALSE, 'I'),
  ('SEN 12', 'Habib Diarra', 'Senegal', 'SEN', 12, 'player', FALSE, 'I'),
  ('SEN 13', 'Team Photo', 'Senegal', 'SEN', 13, 'team_photo', FALSE, 'I'),
  ('SEN 14', 'Lamine Camara', 'Senegal', 'SEN', 14, 'player', FALSE, 'I'),
  ('SEN 15', 'Sadio Mane', 'Senegal', 'SEN', 15, 'player', FALSE, 'I'),
  ('SEN 16', 'Ismaïla Sarr', 'Senegal', 'SEN', 16, 'player', FALSE, 'I'),
  ('SEN 17', 'Boulaye Dia', 'Senegal', 'SEN', 17, 'player', FALSE, 'I'),
  ('SEN 18', 'Iliman Ndiaye', 'Senegal', 'SEN', 18, 'player', FALSE, 'I'),
  ('SEN 19', 'Nicolas Jackson', 'Senegal', 'SEN', 19, 'player', FALSE, 'I'),
  ('SEN 20', 'Krepin Diatta', 'Senegal', 'SEN', 20, 'player', FALSE, 'I'),
  ('IRQ 1', 'Team Logo', 'Iraq', 'IRQ', 1, 'team_logo', TRUE, 'I'),
  ('IRQ 2', 'Jalal Hassan', 'Iraq', 'IRQ', 2, 'player', FALSE, 'I'),
  ('IRQ 3', 'Rebin Sulaka', 'Iraq', 'IRQ', 3, 'player', FALSE, 'I'),
  ('IRQ 4', 'Hussein Ali', 'Iraq', 'IRQ', 4, 'player', FALSE, 'I'),
  ('IRQ 5', 'Akam Hashem', 'Iraq', 'IRQ', 5, 'player', FALSE, 'I'),
  ('IRQ 6', 'Merchas Doski', 'Iraq', 'IRQ', 6, 'player', FALSE, 'I'),
  ('IRQ 7', 'Zaid Tahseen', 'Iraq', 'IRQ', 7, 'player', FALSE, 'I'),
  ('IRQ 8', 'Manaf Younis', 'Iraq', 'IRQ', 8, 'player', FALSE, 'I'),
  ('IRQ 9', 'Zidane Iqbal', 'Iraq', 'IRQ', 9, 'player', FALSE, 'I'),
  ('IRQ 10', 'Amir Al-Ammari', 'Iraq', 'IRQ', 10, 'player', FALSE, 'I'),
  ('IRQ 11', 'Ibrahim Bavesh', 'Iraq', 'IRQ', 11, 'player', FALSE, 'I'),
  ('IRQ 12', 'Ali Jasim', 'Iraq', 'IRQ', 12, 'player', FALSE, 'I'),
  ('IRQ 13', 'Team Photo', 'Iraq', 'IRQ', 13, 'team_photo', FALSE, 'I'),
  ('IRQ 14', 'Youssef Amyn', 'Iraq', 'IRQ', 14, 'player', FALSE, 'I'),
  ('IRQ 15', 'Aimar Sher', 'Iraq', 'IRQ', 15, 'player', FALSE, 'I'),
  ('IRQ 16', 'Marko Farji', 'Iraq', 'IRQ', 16, 'player', FALSE, 'I'),
  ('IRQ 17', 'Osama Rashid', 'Iraq', 'IRQ', 17, 'player', FALSE, 'I'),
  ('IRQ 18', 'Ali Al-Hamadi', 'Iraq', 'IRQ', 18, 'player', FALSE, 'I'),
  ('IRQ 19', 'Aymen Hussein', 'Iraq', 'IRQ', 19, 'player', FALSE, 'I'),
  ('IRQ 20', 'Mohanad Ali', 'Iraq', 'IRQ', 20, 'player', FALSE, 'I'),
  ('NOR 1', 'Team Logo', 'Norway', 'NOR', 1, 'team_logo', TRUE, 'I'),
  ('NOR 2', 'Orjan Nyland', 'Norway', 'NOR', 2, 'player', FALSE, 'I'),
  ('NOR 3', 'Julian Ryerson', 'Norway', 'NOR', 3, 'player', FALSE, 'I'),
  ('NOR 4', 'Leo Ostigård', 'Norway', 'NOR', 4, 'player', FALSE, 'I'),
  ('NOR 5', 'Kristoffer Vassbakk Ajer', 'Norway', 'NOR', 5, 'player', FALSE, 'I'),
  ('NOR 6', 'Marcus Holmgren Pedersen', 'Norway', 'NOR', 6, 'player', FALSE, 'I'),
  ('NOR 7', 'David Møller Wolfe', 'Norway', 'NOR', 7, 'player', FALSE, 'I'),
  ('NOR 8', 'Torbjørn Heggem', 'Norway', 'NOR', 8, 'player', FALSE, 'I'),
  ('NOR 9', 'Morten Thorsby', 'Norway', 'NOR', 9, 'player', FALSE, 'I'),
  ('NOR 10', 'Martin Ødegaard', 'Norway', 'NOR', 10, 'player', FALSE, 'I'),
  ('NOR 11', 'Sander Berge', 'Norway', 'NOR', 11, 'player', FALSE, 'I'),
  ('NOR 12', 'Andreas Schjelderup', 'Norway', 'NOR', 12, 'player', FALSE, 'I'),
  ('NOR 13', 'Team Photo', 'Norway', 'NOR', 13, 'team_photo', FALSE, 'I'),
  ('NOR 14', 'Patrick Berg', 'Norway', 'NOR', 14, 'player', FALSE, 'I'),
  ('NOR 15', 'Erling Haaland', 'Norway', 'NOR', 15, 'player', FALSE, 'I'),
  ('NOR 16', 'Alexander Sørloth', 'Norway', 'NOR', 16, 'player', FALSE, 'I'),
  ('NOR 17', 'Aron Dønnum', 'Norway', 'NOR', 17, 'player', FALSE, 'I'),
  ('NOR 18', 'Jorgen Strand Larsen', 'Norway', 'NOR', 18, 'player', FALSE, 'I'),
  ('NOR 19', 'Antonio Nusa', 'Norway', 'NOR', 19, 'player', FALSE, 'I'),
  ('NOR 20', 'Oscar Bobb', 'Norway', 'NOR', 20, 'player', FALSE, 'I'),
  ('ARG 1', 'Team Logo', 'Argentina', 'ARG', 1, 'team_logo', TRUE, 'J'),
  ('ARG 2', 'Emiliano Martinez', 'Argentina', 'ARG', 2, 'player', FALSE, 'J'),
  ('ARG 3', 'Nahuel Molina', 'Argentina', 'ARG', 3, 'player', FALSE, 'J'),
  ('ARG 4', 'Cristian Romero', 'Argentina', 'ARG', 4, 'player', FALSE, 'J'),
  ('ARG 5', 'Nicolas Otamendi', 'Argentina', 'ARG', 5, 'player', FALSE, 'J'),
  ('ARG 6', 'Nicolas Tagliafico', 'Argentina', 'ARG', 6, 'player', FALSE, 'J'),
  ('ARG 7', 'Leonardo Balerdi', 'Argentina', 'ARG', 7, 'player', FALSE, 'J'),
  ('ARG 8', 'Enzo Fernandez', 'Argentina', 'ARG', 8, 'player', FALSE, 'J'),
  ('ARG 9', 'Alexis Mac Allister', 'Argentina', 'ARG', 9, 'player', FALSE, 'J'),
  ('ARG 10', 'Rodrigo De Paul', 'Argentina', 'ARG', 10, 'player', FALSE, 'J'),
  ('ARG 11', 'Exequiel Palacios', 'Argentina', 'ARG', 11, 'player', FALSE, 'J'),
  ('ARG 12', 'Leandro Paredes', 'Argentina', 'ARG', 12, 'player', FALSE, 'J'),
  ('ARG 13', 'Team Photo', 'Argentina', 'ARG', 13, 'team_photo', FALSE, 'J'),
  ('ARG 14', 'Nico Paz', 'Argentina', 'ARG', 14, 'player', FALSE, 'J'),
  ('ARG 15', 'Franco Mastantuono', 'Argentina', 'ARG', 15, 'player', FALSE, 'J'),
  ('ARG 16', 'Nico Gonzalez', 'Argentina', 'ARG', 16, 'player', FALSE, 'J'),
  ('ARG 17', 'Lionel Messi', 'Argentina', 'ARG', 17, 'player', FALSE, 'J'),
  ('ARG 18', 'Lautaro Martinez', 'Argentina', 'ARG', 18, 'player', FALSE, 'J'),
  ('ARG 19', 'Julian Alvarez', 'Argentina', 'ARG', 19, 'player', FALSE, 'J'),
  ('ARG 20', 'Giuliano Simeone', 'Argentina', 'ARG', 20, 'player', FALSE, 'J'),
  ('ALG 1', 'Team Logo', 'Algeria', 'ALG', 1, 'team_logo', TRUE, 'J'),
  ('ALG 2', 'Alexis Guendouz', 'Algeria', 'ALG', 2, 'player', FALSE, 'J'),
  ('ALG 3', 'Ramy Bensebaini', 'Algeria', 'ALG', 3, 'player', FALSE, 'J'),
  ('ALG 4', 'Youcef Atal', 'Algeria', 'ALG', 4, 'player', FALSE, 'J'),
  ('ALG 5', 'Rayan Aït-Nouri', 'Algeria', 'ALG', 5, 'player', FALSE, 'J'),
  ('ALG 6', 'Mohamed Amine Tougai', 'Algeria', 'ALG', 6, 'player', FALSE, 'J'),
  ('ALG 7', 'Aïssa Mandi', 'Algeria', 'ALG', 7, 'player', FALSE, 'J'),
  ('ALG 8', 'Ismael Bennacer', 'Algeria', 'ALG', 8, 'player', FALSE, 'J'),
  ('ALG 9', 'Houssem Aquar', 'Algeria', 'ALG', 9, 'player', FALSE, 'J'),
  ('ALG 10', 'Hicham Boudaoui', 'Algeria', 'ALG', 10, 'player', FALSE, 'J'),
  ('ALG 11', 'Ramiz Zerrouki', 'Algeria', 'ALG', 11, 'player', FALSE, 'J'),
  ('ALG 12', 'Nabil Bentalab', 'Algeria', 'ALG', 12, 'player', FALSE, 'J'),
  ('ALG 13', 'Team Photo', 'Algeria', 'ALG', 13, 'team_photo', FALSE, 'J'),
  ('ALG 14', 'Farés Chaibi', 'Algeria', 'ALG', 14, 'player', FALSE, 'J'),
  ('ALG 15', 'Riyad Mahrez', 'Algeria', 'ALG', 15, 'player', FALSE, 'J'),
  ('ALG 16', 'Said Benrahma', 'Algeria', 'ALG', 16, 'player', FALSE, 'J'),
  ('ALG 17', 'Anis Hadj Moussa', 'Algeria', 'ALG', 17, 'player', FALSE, 'J'),
  ('ALG 18', 'Amine Gouiri', 'Algeria', 'ALG', 18, 'player', FALSE, 'J'),
  ('ALG 19', 'Baghdad Bounedjah', 'Algeria', 'ALG', 19, 'player', FALSE, 'J'),
  ('ALG 20', 'Mohammed Amoura', 'Algeria', 'ALG', 20, 'player', FALSE, 'J'),
  ('AUT 1', 'Team Logo', 'Austria', 'AUT', 1, 'team_logo', TRUE, 'J'),
  ('AUT 2', 'Alexander Schlager', 'Austria', 'AUT', 2, 'player', FALSE, 'J'),
  ('AUT 3', 'Patrick Pentz', 'Austria', 'AUT', 3, 'player', FALSE, 'J'),
  ('AUT 4', 'David Alaba', 'Austria', 'AUT', 4, 'player', FALSE, 'J'),
  ('AUT 5', 'Kevin Danso', 'Austria', 'AUT', 5, 'player', FALSE, 'J'),
  ('AUT 6', 'Philipp Lienhart', 'Austria', 'AUT', 6, 'player', FALSE, 'J'),
  ('AUT 7', 'Stefan Posch', 'Austria', 'AUT', 7, 'player', FALSE, 'J'),
  ('AUT 8', 'Phillipp Mwene', 'Austria', 'AUT', 8, 'player', FALSE, 'J'),
  ('AUT 9', 'Alexander Prass', 'Austria', 'AUT', 9, 'player', FALSE, 'J'),
  ('AUT 10', 'Xaver Schlager', 'Austria', 'AUT', 10, 'player', FALSE, 'J'),
  ('AUT 11', 'Marcel Sabitzer', 'Austria', 'AUT', 11, 'player', FALSE, 'J'),
  ('AUT 12', 'Konrad Laimer', 'Austria', 'AUT', 12, 'player', FALSE, 'J'),
  ('AUT 13', 'Team Photo', 'Austria', 'AUT', 13, 'team_photo', FALSE, 'J'),
  ('AUT 14', 'Florian Grillitsch', 'Austria', 'AUT', 14, 'player', FALSE, 'J'),
  ('AUT 15', 'Nicolas Seiwald', 'Austria', 'AUT', 15, 'player', FALSE, 'J'),
  ('AUT 16', 'Romano Schmid', 'Austria', 'AUT', 16, 'player', FALSE, 'J'),
  ('AUT 17', 'Patrick Wimmer', 'Austria', 'AUT', 17, 'player', FALSE, 'J'),
  ('AUT 18', 'Christoph Baumgartner', 'Austria', 'AUT', 18, 'player', FALSE, 'J'),
  ('AUT 19', 'Michael Gregoritsch', 'Austria', 'AUT', 19, 'player', FALSE, 'J'),
  ('AUT 20', 'Marko Arnautović', 'Austria', 'AUT', 20, 'player', FALSE, 'J'),
  ('JOR 1', 'Team Logo', 'Jordan', 'JOR', 1, 'team_logo', TRUE, 'J'),
  ('JOR 2', 'Yazeed Abulaila', 'Jordan', 'JOR', 2, 'player', FALSE, 'J'),
  ('JOR 3', 'Ihsan Haddad', 'Jordan', 'JOR', 3, 'player', FALSE, 'J'),
  ('JOR 4', 'Mohammad Abu Hashish', 'Jordan', 'JOR', 4, 'player', FALSE, 'J'),
  ('JOR 5', 'Yazan Al-Arab', 'Jordan', 'JOR', 5, 'player', FALSE, 'J'),
  ('JOR 6', 'Abdallah Nasib', 'Jordan', 'JOR', 6, 'player', FALSE, 'J'),
  ('JOR 7', 'Saleem Obaid', 'Jordan', 'JOR', 7, 'player', FALSE, 'J'),
  ('JOR 8', 'Mohammad Abualnadi', 'Jordan', 'JOR', 8, 'player', FALSE, 'J'),
  ('JOR 9', 'Ibrahim Saadeh', 'Jordan', 'JOR', 9, 'player', FALSE, 'J'),
  ('JOR 10', 'Nizar Al-Rashdan', 'Jordan', 'JOR', 10, 'player', FALSE, 'J'),
  ('JOR 11', 'Noor Al-Rawabdeh', 'Jordan', 'JOR', 11, 'player', FALSE, 'J'),
  ('JOR 12', 'Mohannad Abu Taha', 'Jordan', 'JOR', 12, 'player', FALSE, 'J'),
  ('JOR 13', 'Team Photo', 'Jordan', 'JOR', 13, 'team_photo', FALSE, 'J'),
  ('JOR 14', 'Amer Jamous', 'Jordan', 'JOR', 14, 'player', FALSE, 'J'),
  ('JOR 15', 'Musa Al-Taamari', 'Jordan', 'JOR', 15, 'player', FALSE, 'J'),
  ('JOR 16', 'Yazan Al-Naimat', 'Jordan', 'JOR', 16, 'player', FALSE, 'J'),
  ('JOR 17', 'Mahmoud Al-Mardi', 'Jordan', 'JOR', 17, 'player', FALSE, 'J'),
  ('JOR 18', 'Ali Olwan', 'Jordan', 'JOR', 18, 'player', FALSE, 'J'),
  ('JOR 19', 'Mohammad Abu Zrayq', 'Jordan', 'JOR', 19, 'player', FALSE, 'J'),
  ('JOR 20', 'Ibrahim Sabra', 'Jordan', 'JOR', 20, 'player', FALSE, 'J'),
  ('POR 1', 'Team Logo', 'Portugal', 'POR', 1, 'team_logo', TRUE, 'K'),
  ('POR 2', 'Diogo Costa', 'Portugal', 'POR', 2, 'player', FALSE, 'K'),
  ('POR 3', 'Jose Sa', 'Portugal', 'POR', 3, 'player', FALSE, 'K'),
  ('POR 4', 'Ruben Dias', 'Portugal', 'POR', 4, 'player', FALSE, 'K'),
  ('POR 5', 'João Cancelo', 'Portugal', 'POR', 5, 'player', FALSE, 'K'),
  ('POR 6', 'Diogo Dalot', 'Portugal', 'POR', 6, 'player', FALSE, 'K'),
  ('POR 7', 'Nuno Mendes', 'Portugal', 'POR', 7, 'player', FALSE, 'K'),
  ('POR 8', 'Gonçalo Inácio', 'Portugal', 'POR', 8, 'player', FALSE, 'K'),
  ('POR 9', 'Bernardo Silva', 'Portugal', 'POR', 9, 'player', FALSE, 'K'),
  ('POR 10', 'Bruno Fernandes', 'Portugal', 'POR', 10, 'player', FALSE, 'K'),
  ('POR 11', 'Ruben Neves', 'Portugal', 'POR', 11, 'player', FALSE, 'K'),
  ('POR 12', 'Vitinha', 'Portugal', 'POR', 12, 'player', FALSE, 'K'),
  ('POR 13', 'Team Photo', 'Portugal', 'POR', 13, 'team_photo', FALSE, 'K'),
  ('POR 14', 'João Neves', 'Portugal', 'POR', 14, 'player', FALSE, 'K'),
  ('POR 15', 'Cristiano Ronaldo', 'Portugal', 'POR', 15, 'player', FALSE, 'K'),
  ('POR 16', 'Francisco Trincao', 'Portugal', 'POR', 16, 'player', FALSE, 'K'),
  ('POR 17', 'João Felix', 'Portugal', 'POR', 17, 'player', FALSE, 'K'),
  ('POR 18', 'Gonçalo Ramos', 'Portugal', 'POR', 18, 'player', FALSE, 'K'),
  ('POR 19', 'Pedro Neto', 'Portugal', 'POR', 19, 'player', FALSE, 'K'),
  ('POR 20', 'Rafael Leão', 'Portugal', 'POR', 20, 'player', FALSE, 'K'),
  ('GHA 1', 'Team Logo', 'Ghana', 'GHA', 1, 'team_logo', TRUE, 'K'),
  ('GHA 2', 'Lawrence Ati Zigi', 'Ghana', 'GHA', 2, 'player', FALSE, 'K'),
  ('GHA 3', 'Tariq Lamptey', 'Ghana', 'GHA', 3, 'player', FALSE, 'K'),
  ('GHA 4', 'Mohammed Salisu', 'Ghana', 'GHA', 4, 'player', FALSE, 'K'),
  ('GHA 5', 'Alidu Seidu', 'Ghana', 'GHA', 5, 'player', FALSE, 'K'),
  ('GHA 6', 'Alexander Djiku', 'Ghana', 'GHA', 6, 'player', FALSE, 'K'),
  ('GHA 7', 'Gideon Mensah', 'Ghana', 'GHA', 7, 'player', FALSE, 'K'),
  ('GHA 8', 'Caleb Yirenkyi', 'Ghana', 'GHA', 8, 'player', FALSE, 'K'),
  ('GHA 9', 'Abdul Issahaku Fatawu', 'Ghana', 'GHA', 9, 'player', FALSE, 'K'),
  ('GHA 10', 'Thomas Partey', 'Ghana', 'GHA', 10, 'player', FALSE, 'K'),
  ('GHA 11', 'Salis Abdul Samed', 'Ghana', 'GHA', 11, 'player', FALSE, 'K'),
  ('GHA 12', 'Kamaldeen Sulemana', 'Ghana', 'GHA', 12, 'player', FALSE, 'K'),
  ('GHA 13', 'Team Photo', 'Ghana', 'GHA', 13, 'team_photo', FALSE, 'K'),
  ('GHA 14', 'Mohammed Kudus', 'Ghana', 'GHA', 14, 'player', FALSE, 'K'),
  ('GHA 15', 'Inaki Williams', 'Ghana', 'GHA', 15, 'player', FALSE, 'K'),
  ('GHA 16', 'Jordan Ayew', 'Ghana', 'GHA', 16, 'player', FALSE, 'K'),
  ('GHA 17', 'Andrew Ayew', 'Ghana', 'GHA', 17, 'player', FALSE, 'K'),
  ('GHA 18', 'Joseph Paintsil', 'Ghana', 'GHA', 18, 'player', FALSE, 'K'),
  ('GHA 19', 'Osman Bukari', 'Ghana', 'GHA', 19, 'player', FALSE, 'K'),
  ('GHA 20', 'Antoine Semenyo', 'Ghana', 'GHA', 20, 'player', FALSE, 'K'),
  ('COL 1', 'Team Logo', 'Colombia', 'COL', 1, 'team_logo', TRUE, 'K'),
  ('COL 2', 'Camilo Vargas', 'Colombia', 'COL', 2, 'player', FALSE, 'K'),
  ('COL 3', 'David Ospina', 'Colombia', 'COL', 3, 'player', FALSE, 'K'),
  ('COL 4', 'Dávinson Sánchez', 'Colombia', 'COL', 4, 'player', FALSE, 'K'),
  ('COL 5', 'Yerry Mina', 'Colombia', 'COL', 5, 'player', FALSE, 'K'),
  ('COL 6', 'Daniel Munoz', 'Colombia', 'COL', 6, 'player', FALSE, 'K'),
  ('COL 7', 'Johan Mojica', 'Colombia', 'COL', 7, 'player', FALSE, 'K'),
  ('COL 8', 'Jhon Lucumí', 'Colombia', 'COL', 8, 'player', FALSE, 'K'),
  ('COL 9', 'Santiago Arias', 'Colombia', 'COL', 9, 'player', FALSE, 'K'),
  ('COL 10', 'Jefferson Lerma', 'Colombia', 'COL', 10, 'player', FALSE, 'K'),
  ('COL 11', 'Kevin Castaño', 'Colombia', 'COL', 11, 'player', FALSE, 'K'),
  ('COL 12', 'Richard Rios', 'Colombia', 'COL', 12, 'player', FALSE, 'K'),
  ('COL 13', 'Team Photo', 'Colombia', 'COL', 13, 'team_photo', FALSE, 'K'),
  ('COL 14', 'James Rodriguez', 'Colombia', 'COL', 14, 'player', FALSE, 'K'),
  ('COL 15', 'Juan Fernando Quintero', 'Colombia', 'COL', 15, 'player', FALSE, 'K'),
  ('COL 16', 'Jorge Carrascal', 'Colombia', 'COL', 16, 'player', FALSE, 'K'),
  ('COL 17', 'Jon Arias', 'Colombia', 'COL', 17, 'player', FALSE, 'K'),
  ('COL 18', 'Jhon Cordova', 'Colombia', 'COL', 18, 'player', FALSE, 'K'),
  ('COL 19', 'Luis Suarez', 'Colombia', 'COL', 19, 'player', FALSE, 'K'),
  ('COL 20', 'Luis Diaz', 'Colombia', 'COL', 20, 'player', FALSE, 'K'),
  ('COD 1', 'Team Logo', 'DR Congo', 'COD', 1, 'team_logo', TRUE, 'K'),
  ('COD 2', 'Lionel Mpasi', 'DR Congo', 'COD', 2, 'player', FALSE, 'K'),
  ('COD 3', 'Aaron Wan-Bissaka', 'DR Congo', 'COD', 3, 'player', FALSE, 'K'),
  ('COD 4', 'Axel Tuanzebe', 'DR Congo', 'COD', 4, 'player', FALSE, 'K'),
  ('COD 5', 'Arthur Masuaku', 'DR Congo', 'COD', 5, 'player', FALSE, 'K'),
  ('COD 6', 'Chancel Mbemba', 'DR Congo', 'COD', 6, 'player', FALSE, 'K'),
  ('COD 7', 'Joris Kayembe', 'DR Congo', 'COD', 7, 'player', FALSE, 'K'),
  ('COD 8', 'Charles Pickel', 'DR Congo', 'COD', 8, 'player', FALSE, 'K'),
  ('COD 9', 'Ngal''ayel Mukau', 'DR Congo', 'COD', 9, 'player', FALSE, 'K'),
  ('COD 10', 'Edo Kayembe', 'DR Congo', 'COD', 10, 'player', FALSE, 'K'),
  ('COD 11', 'Samuel Moutoussamy', 'DR Congo', 'COD', 11, 'player', FALSE, 'K'),
  ('COD 12', 'Noah Sadiki', 'DR Congo', 'COD', 12, 'player', FALSE, 'K'),
  ('COD 13', 'Team Photo', 'DR Congo', 'COD', 13, 'team_photo', FALSE, 'K'),
  ('COD 14', 'Théo Bongonda', 'DR Congo', 'COD', 14, 'player', FALSE, 'K'),
  ('COD 15', 'Meschak Elia', 'DR Congo', 'COD', 15, 'player', FALSE, 'K'),
  ('COD 16', 'Yoane Wissa', 'DR Congo', 'COD', 16, 'player', FALSE, 'K'),
  ('COD 17', 'Brian Cipenga', 'DR Congo', 'COD', 17, 'player', FALSE, 'K'),
  ('COD 18', 'Fiston Mayele', 'DR Congo', 'COD', 18, 'player', FALSE, 'K'),
  ('COD 19', 'Cédric Bakambu', 'DR Congo', 'COD', 19, 'player', FALSE, 'K'),
  ('COD 20', 'Nathanaël Mbuku', 'DR Congo', 'COD', 20, 'player', FALSE, 'K'),
  ('PAN 1', 'Team Logo', 'Panama', 'PAN', 1, 'team_logo', TRUE, 'L'),
  ('PAN 2', 'Orlando Mosquera', 'Panama', 'PAN', 2, 'player', FALSE, 'L'),
  ('PAN 3', 'Luis Mejia', 'Panama', 'PAN', 3, 'player', FALSE, 'L'),
  ('PAN 4', 'Fidel Escobar', 'Panama', 'PAN', 4, 'player', FALSE, 'L'),
  ('PAN 5', 'Andres Andrade', 'Panama', 'PAN', 5, 'player', FALSE, 'L'),
  ('PAN 6', 'Michael Amir Murillo', 'Panama', 'PAN', 6, 'player', FALSE, 'L'),
  ('PAN 7', 'Eric Davis', 'Panama', 'PAN', 7, 'player', FALSE, 'L'),
  ('PAN 8', 'Jose Cordoba', 'Panama', 'PAN', 8, 'player', FALSE, 'L'),
  ('PAN 9', 'Cesar Blackman', 'Panama', 'PAN', 9, 'player', FALSE, 'L'),
  ('PAN 10', 'Cristian Martinez', 'Panama', 'PAN', 10, 'player', FALSE, 'L'),
  ('PAN 11', 'Aníbal Godoy', 'Panama', 'PAN', 11, 'player', FALSE, 'L'),
  ('PAN 12', 'Adalberto Carrasquilla', 'Panama', 'PAN', 12, 'player', FALSE, 'L'),
  ('PAN 13', 'Team Photo', 'Panama', 'PAN', 13, 'team_photo', FALSE, 'L'),
  ('PAN 14', 'Édgar Bárcenas', 'Panama', 'PAN', 14, 'player', FALSE, 'L'),
  ('PAN 15', 'Carlos Harvey', 'Panama', 'PAN', 15, 'player', FALSE, 'L'),
  ('PAN 16', 'Ismael Díaz', 'Panama', 'PAN', 16, 'player', FALSE, 'L'),
  ('PAN 17', 'Jose Fajardo', 'Panama', 'PAN', 17, 'player', FALSE, 'L'),
  ('PAN 18', 'Cecilio Waterman', 'Panama', 'PAN', 18, 'player', FALSE, 'L'),
  ('PAN 19', 'Jose Luiz Rodriguez', 'Panama', 'PAN', 19, 'player', FALSE, 'L'),
  ('PAN 20', 'Alberto Quintero', 'Panama', 'PAN', 20, 'player', FALSE, 'L'),
  ('UZB 1', 'Team Logo', 'Uzbekistan', 'UZB', 1, 'team_logo', TRUE, 'L'),
  ('UZB 2', 'Utkir Yusupov', 'Uzbekistan', 'UZB', 2, 'player', FALSE, 'L'),
  ('UZB 3', 'Farrukh Savfiev', 'Uzbekistan', 'UZB', 3, 'player', FALSE, 'L'),
  ('UZB 4', 'Sherzod Nasrullaev', 'Uzbekistan', 'UZB', 4, 'player', FALSE, 'L'),
  ('UZB 5', 'Umar Eshmurodov', 'Uzbekistan', 'UZB', 5, 'player', FALSE, 'L'),
  ('UZB 6', 'Husniddin Aliqulov', 'Uzbekistan', 'UZB', 6, 'player', FALSE, 'L'),
  ('UZB 7', 'Rustamjon Ashurmatov', 'Uzbekistan', 'UZB', 7, 'player', FALSE, 'L'),
  ('UZB 8', 'Khojiakbar Alijonov', 'Uzbekistan', 'UZB', 8, 'player', FALSE, 'L'),
  ('UZB 9', 'Abdukodir Khusanov', 'Uzbekistan', 'UZB', 9, 'player', FALSE, 'L'),
  ('UZB 10', 'Odiljon Hamrobekov', 'Uzbekistan', 'UZB', 10, 'player', FALSE, 'L'),
  ('UZB 11', 'Otabek Shukurov', 'Uzbekistan', 'UZB', 11, 'player', FALSE, 'L'),
  ('UZB 12', 'Jamshid Iskanderov', 'Uzbekistan', 'UZB', 12, 'player', FALSE, 'L'),
  ('UZB 13', 'Team Photo', 'Uzbekistan', 'UZB', 13, 'team_photo', FALSE, 'L'),
  ('UZB 14', 'Azizbek Turgunboev', 'Uzbekistan', 'UZB', 14, 'player', FALSE, 'L'),
  ('UZB 15', 'Khojimat Erkinov', 'Uzbekistan', 'UZB', 15, 'player', FALSE, 'L'),
  ('UZB 16', 'Eldor Shomurodov', 'Uzbekistan', 'UZB', 16, 'player', FALSE, 'L'),
  ('UZB 17', 'Oston Urunov', 'Uzbekistan', 'UZB', 17, 'player', FALSE, 'L'),
  ('UZB 18', 'Jaloliddin Masharipov', 'Uzbekistan', 'UZB', 18, 'player', FALSE, 'L'),
  ('UZB 19', 'Igor Sergeev', 'Uzbekistan', 'UZB', 19, 'player', FALSE, 'L'),
  ('UZB 20', 'Abbosbek Fayzullaev', 'Uzbekistan', 'UZB', 20, 'player', FALSE, 'L'),
  ('CRO 1', 'Team Logo', 'Croatia', 'CRO', 1, 'team_logo', TRUE, 'L'),
  ('CRO 2', 'Dominik Livaković', 'Croatia', 'CRO', 2, 'player', FALSE, 'L'),
  ('CRO 3', 'Duje Caleta-Car', 'Croatia', 'CRO', 3, 'player', FALSE, 'L'),
  ('CRO 4', 'Josko Gvardiol', 'Croatia', 'CRO', 4, 'player', FALSE, 'L'),
  ('CRO 5', 'Josip Stanišić', 'Croatia', 'CRO', 5, 'player', FALSE, 'L'),
  ('CRO 6', 'Luka Vušković', 'Croatia', 'CRO', 6, 'player', FALSE, 'L'),
  ('CRO 7', 'Josip Sutalo', 'Croatia', 'CRO', 7, 'player', FALSE, 'L'),
  ('CRO 8', 'Kristijan Jakic', 'Croatia', 'CRO', 8, 'player', FALSE, 'L'),
  ('CRO 9', 'Luka Modrić', 'Croatia', 'CRO', 9, 'player', FALSE, 'L'),
  ('CRO 10', 'Mateo Kovacic', 'Croatia', 'CRO', 10, 'player', FALSE, 'L'),
  ('CRO 11', 'Martin Baturina', 'Croatia', 'CRO', 11, 'player', FALSE, 'L'),
  ('CRO 12', 'Lovro Majer', 'Croatia', 'CRO', 12, 'player', FALSE, 'L'),
  ('CRO 13', 'Team Photo', 'Croatia', 'CRO', 13, 'team_photo', FALSE, 'L'),
  ('CRO 14', 'Mario Pasalic', 'Croatia', 'CRO', 14, 'player', FALSE, 'L'),
  ('CRO 15', 'Petar Sucic', 'Croatia', 'CRO', 15, 'player', FALSE, 'L'),
  ('CRO 16', 'Ivan Perišić', 'Croatia', 'CRO', 16, 'player', FALSE, 'L'),
  ('CRO 17', 'Marco Pasalic', 'Croatia', 'CRO', 17, 'player', FALSE, 'L'),
  ('CRO 18', 'Ante Budimir', 'Croatia', 'CRO', 18, 'player', FALSE, 'L'),
  ('CRO 19', 'Andrej Kramarić', 'Croatia', 'CRO', 19, 'player', FALSE, 'L'),
  ('CRO 20', 'Franjo Ivanovic', 'Croatia', 'CRO', 20, 'player', FALSE, 'L'),
  ('ENG 1', 'Team Logo', 'England', 'ENG', 1, 'team_logo', TRUE, 'L'),
  ('ENG 2', 'Jordan Pickford', 'England', 'ENG', 2, 'player', FALSE, 'L'),
  ('ENG 3', 'John Stones', 'England', 'ENG', 3, 'player', FALSE, 'L'),
  ('ENG 4', 'Marc Guéhi', 'England', 'ENG', 4, 'player', FALSE, 'L'),
  ('ENG 5', 'Ezri Konsa', 'England', 'ENG', 5, 'player', FALSE, 'L'),
  ('ENG 6', 'Trent Alexander-Arnold', 'England', 'ENG', 6, 'player', FALSE, 'L'),
  ('ENG 7', 'Reece James', 'England', 'ENG', 7, 'player', FALSE, 'L'),
  ('ENG 8', 'Dan Burn', 'England', 'ENG', 8, 'player', FALSE, 'L'),
  ('ENG 9', 'Jordan Henderson', 'England', 'ENG', 9, 'player', FALSE, 'L'),
  ('ENG 10', 'Declan Rice', 'England', 'ENG', 10, 'player', FALSE, 'L'),
  ('ENG 11', 'Jude Bellingham', 'England', 'ENG', 11, 'player', FALSE, 'L'),
  ('ENG 12', 'Cole Palmer', 'England', 'ENG', 12, 'player', FALSE, 'L'),
  ('ENG 13', 'Team Photo', 'England', 'ENG', 13, 'team_photo', FALSE, 'L'),
  ('ENG 14', 'Morgan Rogers', 'England', 'ENG', 14, 'player', FALSE, 'L'),
  ('ENG 15', 'Anthony Gordon', 'England', 'ENG', 15, 'player', FALSE, 'L'),
  ('ENG 16', 'Phil Foden', 'England', 'ENG', 16, 'player', FALSE, 'L'),
  ('ENG 17', 'Bukayo Saka', 'England', 'ENG', 17, 'player', FALSE, 'L'),
  ('ENG 18', 'Harry Kane', 'England', 'ENG', 18, 'player', FALSE, 'L'),
  ('ENG 19', 'Marcus Rashford', 'England', 'ENG', 19, 'player', FALSE, 'L'),
  ('ENG 20', 'Ollie Watkins', 'England', 'ENG', 20, 'player', FALSE, 'L'),
  ('FWC 9', 'Italy 1934 - World Cup History', 'World Cup History', 'FWC', 9, 'fwc_special', TRUE, ''),
  ('FWC 10', 'Uruguay 1950 - World Cup History', 'World Cup History', 'FWC', 10, 'fwc_special', TRUE, ''),
  ('FWC 11', 'West Germany 1954 - World Cup History', 'World Cup History', 'FWC', 11, 'fwc_special', TRUE, ''),
  ('FWC 12', 'Brazil 1962 - World Cup History', 'World Cup History', 'FWC', 12, 'fwc_special', TRUE, ''),
  ('FWC 13', 'West Germany 1974 - World Cup History', 'World Cup History', 'FWC', 13, 'fwc_special', TRUE, ''),
  ('FWC 14', 'Argentina 1986 - World Cup History', 'World Cup History', 'FWC', 14, 'fwc_special', TRUE, ''),
  ('FWC 15', 'Brazil 1994 - World Cup History', 'World Cup History', 'FWC', 15, 'fwc_special', TRUE, ''),
  ('FWC 16', 'Brazil 2002 - World Cup History', 'World Cup History', 'FWC', 16, 'fwc_special', TRUE, ''),
  ('FWC 17', 'Italy 2006 - World Cup History', 'World Cup History', 'FWC', 17, 'fwc_special', TRUE, ''),
  ('FWC 18', 'Germany 2014 - World Cup History', 'World Cup History', 'FWC', 18, 'fwc_special', TRUE, ''),
  ('FWC 19', 'Argentina 2022 - World Cup History', 'World Cup History', 'FWC', 19, 'fwc_special', TRUE, '');
 
-- Verify: SELECT COUNT(*) FROM stickers; -- should return 980